import pprint

leagues = {
    'Baseball': ['MLB', 'KBO', 'MexicanLMB', 'NPB', 'CPBL'],
    'Basketball': ['WNBA', 'EuroLeague', 'GermanyBBL', 'ItalyLega', 'VTBUnited', 'SuperLig', 'SuperLeague', 'NBA',
                   'NCAABasketball', 'GreekBasketball', 'Eurocup', 'SpainACB', 'FranceLNB', 'NBLAustralia'],
    'Tennis': ['ATPRome', 'WTARome', 'ATPGeneva', 'ATPLyon', 'WTAStrasbourg', 'WTARabat', 'ChallengerShykent2'],
    'Soccer': ['MLS', 'EPL', 'SpanishLaLiga', 'SerieA', 'Ligue1', 'Bundesliga', 'PrimeraDivision', 'BrazilSerieB', 'PremierLeague',
               'ChinaSuperLeague', 'BrazilSerieA', 'UruguayPrimeraDivision', 'SwedenAllsvenskan', 'SwedenSuperettan',
               'SouthKoreaLeague1', 'PeruLiga1', 'ParaguayPrimeraDivision'],
    'Football': ['NFL'],
    'Hockey': ['NHL']
}

oddsportal_urls = {
    'WNBA': 'basketball/usa/wnba',
    'BrazilSerieA': 'soccer/brazil/serie-a',
    'ATPRome': 'tennis/italy/atp-rome',
    'WTARome': 'tennis/italy/wta-rome',
    'ATPGeneva': 'tennis/switzerland/atp-geneva',
    'ATPLyon': 'tennis/france/atp-lyon',
    'WTAStrasbourg': 'tennis/france/wta-strasbourg',
    'WTARabat': 'tennis/morocco/wta-rabat',
    'ChallengerShymkent2': 'tennis/kazakhstan/shymkent-2-challenger-men',
    'MLS': 'soccer/usa/mls',
    'EPL': 'soccer/england/premier-league',
    'ATPFrenchOpen': 'tennis/france/atp-french-open',
    'KBO': 'baseball/south-korea/kbo',
    'MexicanLMB': 'baseball/mexico/lmb',
    'EuroLeague': 'basketball/europe/euroleague',
    'GermanyBBL': 'basketball/germany/bbl',
    'ItalyLega': 'basketball/italy/lega-a',
    'VTBUnited': 'basketball/russia/vtb-united-league',
    'SuperLig': 'basketball/turkey/super-lig',
    'SuperLeague': 'basketball/israel/super-league',
    'SpanishLaLiga': 'soccer/spain/laliga',
    'SerieA': 'soccer/italy/serie-a',
    'Ligue1': 'soccer/france/ligue-1',
    'Bundesliga': 'soccer/germany/bundesliga',
    'CPBL': 'baseball/taiwan/cpbl',
    'PrimeraDivision': 'soccer/argentina/liga-profesional',
    'NPB': 'baseball/japan/npb',
    'BrazilSerieB': 'soccer/brazil/serie-b',
    'ChinaSuperLeague': 'soccer/china/super-league',
    'SwedenAllsvenskan': 'soccer/sweden/allsvenskan',
    'SwedenSuperettan': 'soccer/sweden/superettan',
    'ParaguayPrimeraDivision': 'soccer/paraguay/primera-division'
}

sr_multi_page = {
    'NPB': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=6ffa4c10',
                                            '2021': 'https://www.baseball-reference.com/register/league.cgi?id=0549ac26',
                                            '2020': 'https://www.baseball-reference.com/register/league.cgi?id=4b244907',
                                            '2019': 'https://www.baseball-reference.com/register/league.cgi?id=7f5a1dca',
                                            '2018': 'https://www.baseball-reference.com/register/league.cgi?id=8449fb1b',
                                            '2017': 'https://www.baseball-reference.com/register/league.cgi?id=5ed71981',
                                            '2016': 'https://www.baseball-reference.com/register/league.cgi?id=fa996fac',
                                            '2015': 'https://www.baseball-reference.com/register/league.cgi?id=ef7a4bc6'
                                            },
            'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'KBO': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=8af2b395',
                                '2021': 'https://www.baseball-reference.com/register/league.cgi?id=bc0c5118',
                                '2020': 'https://www.baseball-reference.com/register/league.cgi?id=17edbc3b',
                                '2019': 'https://www.baseball-reference.com/register/league.cgi?id=6a2bec36',
                                '2018': 'https://www.baseball-reference.com/register/league.cgi?id=3ef9029d',
                                '2017': 'https://www.baseball-reference.com/register/league.cgi?id=8aa559d8',
                                '2016': 'https://www.baseball-reference.com/register/league.cgi?id=8f7d6569',
                                '2015': 'https://www.baseball-reference.com/register/league.cgi?id=dffe1d5e'
                                },
                                'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'MexicanLMB': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=73c8b264',
                                '2021': 'https://www.baseball-reference.com/register/league.cgi?id=4d19918d',
                                '2020': '',
                                '2019': 'https://www.baseball-reference.com/register/league.cgi?id=92f1b3e0',
                                '2018': '',
                                '2017': 'https://www.baseball-reference.com/register/league.cgi?id=1a0ab508',
                                '2016': 'https://www.baseball-reference.com/register/league.cgi?id=6939d532',
                                '2015': 'https://www.baseball-reference.com/register/league.cgi?id=60e641d9'
                                },
                                'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'EPL': {'urls': {'2022': 'https://fbref.com/en/comps/9/Premier-League-Stats',
                                '2021': 'https://fbref.com/en/comps/9/10728/2020-2021-Premier-League-Stats',
                                '2020': 'https://fbref.com/en/comps/9/3232/2019-2020-Premier-League-Stats',
                                '2019': 'https://fbref.com/en/comps/9/1889/2018-2019-Premier-League-Stats',
                                '2018': 'https://fbref.com/en/comps/9/1631/2017-2018-Premier-League-Stats',
                                '2017': 'https://fbref.com/en/comps/9/1526/2016-2017-Premier-League-Stats',
                                '2016': 'https://fbref.com/en/comps/9/1467/2015-2016-Premier-League-Stats',
                                '2015': 'https://fbref.com/en/comps/9/733/2014-2015-Premier-League-Stats'
                                },
                                'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'SpanishLaLiga': {'urls': {'2022': 'https://fbref.com/en/comps/12/La-Liga-Stats',
                                   '2021': 'https://fbref.com/en/comps/12/10731/2020-2021-La-Liga-Stats',
                                   '2020': 'https://fbref.com/en/comps/12/3239/2019-2020-La-Liga-Stats',
                                   '2019': 'https://fbref.com/en/comps/12/1886/2018-2019-La-Liga-Stats',
                                   '2018': 'https://fbref.com/en/comps/12/1652/2017-2018-La-Liga-Stats',
                                   '2017': 'https://fbref.com/en/comps/12/1547/2016-2017-La-Liga-Stats',
                                   '2016': 'https://fbref.com/en/comps/12/1488/2015-2016-La-Liga-Stats',
                                   '2015': 'https://fbref.com/en/comps/12/755/2014-2015-La-Liga-Stats'
                                   },
                                   'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'SerieA': {'urls': {'2022': 'https://fbref.com/en/comps/11/Serie-A-Stats',
                                   '2021': 'https://fbref.com/en/comps/11/10730/2020-2021-Serie-A-Stats',
                                   '2020': 'https://fbref.com/en/comps/11/3260/2019-2020-Serie-A-Stats',
                                   '2019': 'https://fbref.com/en/comps/11/1896/2018-2019-Serie-A-Stats',
                                   '2018': 'https://fbref.com/en/comps/11/1640/2017-2018-Serie-A-Stats',
                                   '2017': 'https://fbref.com/en/comps/11/1535/2016-2017-Serie-A-Stats',
                                   '2016': 'https://fbref.com/en/comps/11/1476/2015-2016-Serie-A-Stats',
                                   '2015': 'https://fbref.com/en/comps/11/742/2014-2015-Serie-A-Stats'
                                   },
                                   'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'Ligue1': {'urls': {'2022': 'https://fbref.com/en/comps/13/Ligue-1-Stats',
                                   '2021': 'https://fbref.com/en/comps/13/10732/2020-2021-Ligue-1-Stats',
                                   '2020': 'https://fbref.com/en/comps/13/3243/2019-2020-Ligue-1-Stats',
                                   '2019': 'https://fbref.com/en/comps/13/2104/2018-2019-Ligue-1-Stats',
                                   '2018': 'https://fbref.com/en/comps/13/1632/2017-2018-Ligue-1-Stats',
                                   '2017': 'https://fbref.com/en/comps/13/1527/2016-2017-Ligue-1-Stats',
                                   '2016': 'https://fbref.com/en/comps/13/1468/2015-2016-Ligue-1-Stats',
                                   '2015': 'https://fbref.com/en/comps/13/734/2014-2015-Ligue-1-Stats'
                                   },
                                   'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'Bundesliga': {'urls': {'2022': 'https://fbref.com/en/comps/20/Bundesliga-Stats',
                                       '2021': 'https://fbref.com/en/comps/20/10737/2020-2021-Bundesliga-Stats',
                                       '2020': 'https://fbref.com/en/comps/20/3248/2019-2020-Bundesliga-Stats',
                                       '2019': 'https://fbref.com/en/comps/20/2109/2018-2019-Bundesliga-Stats',
                                       '2018': 'https://fbref.com/en/comps/20/1634/2017-2018-Bundesliga-Stats',
                                       '2017': 'https://fbref.com/en/comps/20/1529/2016-2017-Bundesliga-Stats',
                                       '2016': 'https://fbref.com/en/comps/20/1470/2015-2016-Bundesliga-Stats',
                                       '2015': 'https://fbref.com/en/comps/20/736/2014-2015-Bundesliga-Stats'
                                       },
                                       'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'MLS': {'urls': {'2022': 'https://fbref.com/en/comps/22/Major-League-Soccer-Stats',
                                       '2021': 'https://fbref.com/en/comps/22/11006/2021-Major-League-Soccer-Stats',
                                       '2020': 'https://fbref.com/en/comps/22/10090/2020-Major-League-Soccer-Stats',
                                       '2019': 'https://fbref.com/en/comps/22/2798/2019-Major-League-Soccer-Stats',
                                       '2018': 'https://fbref.com/en/comps/22/1759/2018-Major-League-Soccer-Stats',
                                       '2017': 'https://fbref.com/en/comps/22/1558/2017-Major-League-Soccer-Stats',
                                       '2016': 'https://fbref.com/en/comps/22/1503/2016-Major-League-Soccer-Stats',
                                       '2015': 'https://fbref.com/en/comps/22/1369/2015-Major-League-Soccer-Stats'
                                       },
                                'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'CPBL': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=c6fb0851',
                                 '2021': 'https://www.baseball-reference.com/register/league.cgi?id=cb99eabd',
                                 '2020': 'https://www.baseball-reference.com/register/league.cgi?id=344a0cc6',
                                 '2019': 'https://www.baseball-reference.com/register/league.cgi?id=148c2608',
                                 '2018': 'https://www.baseball-reference.com/register/league.cgi?id=465932ad',
                                 '2017': 'https://www.baseball-reference.com/register/league.cgi?id=997b98a9',
                                 '2016': 'https://www.baseball-reference.com/register/league.cgi?id=4f106647',
                                 '2015': 'https://www.baseball-reference.com/register/league.cgi?id=dafaa05c'
                                 },
                                 'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'PrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/21/Primera-Division-Stats',
                                            '2021': 'https://fbref.com/en/comps/21/10738/2021-Primera-Division-Stats',
                                            '2020': 'https://fbref.com/en/comps/21/3211/2019-2020-Superliga-Argentina-Stats',
                                            '2019': 'https://fbref.com/en/comps/21/2436/2018-2019-Superliga-Argentina-Stats',
                                            '2018': 'https://fbref.com/en/comps/21/1659/2017-2018-Superliga-Argentina-Stats',
                                            '2017': 'https://fbref.com/en/comps/21/1554/2016-2017-Primera-Division-Stats',
                                            '2016': 'https://fbref.com/en/comps/21/1494/2016-Primera-Division-Stats',
                                            '2015': 'https://fbref.com/en/comps/21/789/2015-Primera-Division-Stats'
                                            },
                                            'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'BrazilSerieA': {'urls': {'2022': 'https://fbref.com/en/comps/24/Serie-A-Stats',
                                         '2021': 'https://fbref.com/en/comps/24/10986/2021-Serie-A-Stats',
                                         '2020': 'https://fbref.com/en/comps/24/10072/2020-Serie-A-Stats',
                                         '2019': 'https://fbref.com/en/comps/24/3320/2019-Serie-A-Stats',
                                         '2018': 'https://fbref.com/en/comps/24/1760/2018-Serie-A-Stats',
                                         '2017': 'https://fbref.com/en/comps/24/1559/2017-Serie-A-Stats',
                                         '2016': 'https://fbref.com/en/comps/24/1495/2016-Serie-A-Stats',
                                         '2015': 'https://fbref.com/en/comps/24/851/2015-Serie-A-Stats'
                                         },
                                         'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'BrazilSerieB': {'urls': {'2022': 'https://fbref.com/en/comps/38/Serie-B-Stats',
                                            '2021': 'https://fbref.com/en/comps/38/10987/2021-Serie-B-Stats',
                                            '2020': 'https://fbref.com/en/comps/38/10073/2020-Serie-B-Stats',
                                            '2019': 'https://fbref.com/en/comps/38/3321/2019-Serie-B-Stats',
                                            '2018': 'https://fbref.com/en/comps/38/1764/2018-Serie-B-Stats',
                                            '2017': 'https://fbref.com/en/comps/38/1563/2017-Serie-B-Stats',
                                            '2016': 'https://fbref.com/en/comps/38/1496/2016-Serie-B-Stats',
                                            '2015': ''},
                                         'xpaths' : ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
    'ChinaSuperLeague': {'urls': {'2022': 'https://fbref.com/en/comps/62/Chinese-Super-League-Stats',
                              '2021': 'https://fbref.com/en/comps/62/10990/2021-Chinese-Super-League-Stats',
                              '2020': 'https://fbref.com/en/comps/62/10075/2020-Chinese-Super-League-Stats',
                              '2019': 'https://fbref.com/en/comps/62/3933/2019-Chinese-Super-League-Stats',
                              '2018': 'https://fbref.com/en/comps/62/1774/2018-Chinese-Super-League-Stats',
                              '2017': 'https://fbref.com/en/comps/62/1578/2017-Chinese-Super-League-Stats',
                              '2016': 'https://fbref.com/en/comps/62/1497/2016-Chinese-Super-League-Stats',
                              '2015': 'https://fbref.com/en/comps/62/897/2015-Chinese-Super-League-Stats'},
                     'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
    'UruguayPrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/45/Primera-Division-Stats',
                                  '2021': 'https://fbref.com/en/comps/45/11005/2021-Primera-Division-Stats',
                                  '2020': 'https://fbref.com/en/comps/45/10089/2020-Primera-Division-Stats',
                                  '2019': 'https://fbref.com/en/comps/45/3929/2019-Primera-Division-Stats',
                                  '2018': 'https://fbref.com/en/comps/45/1768/2018-Primera-Division-Stats',
                                  '2017': 'https://fbref.com/en/comps/45/1569/2017-Primera-Division-Stats',
                                  '2016': 'https://fbref.com/en/comps/45/1570/2016-Primera-Division-Stats',
                                  '2015': 'https://fbref.com/en/comps/45/1493/2015-2016-Primera-Division-Stats'},
                         'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
    'SwedenAllsvenskan': {'urls': {'2022': 'https://fbref.com/en/comps/29/Allsvenskan-Stats',
                                        '2021': 'https://fbref.com/en/comps/29/11002/2021-Allsvenskan-Stats',
                                        '2020': 'https://fbref.com/en/comps/29/10086/2020-Allsvenskan-Stats',
                                        '2019': 'https://fbref.com/en/comps/29/2917/2019-Allsvenskan-Stats',
                                        '2018': 'https://fbref.com/en/comps/29/1763/2018-Allsvenskan-Stats',
                                        '2017': 'https://fbref.com/en/comps/29/1562/2017-Allsvenskan-Stats',
                                        '2016': 'https://fbref.com/en/comps/29/1509/2016-Allsvenskan-Stats',
                                        '2015': 'https://fbref.com/en/comps/29/1348/2015-Allsvenskan-Stats'},
                               'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                          '//*[@id="stats_squads_keeper_for"]']},
    'SwedenSuperettan': {'urls': {'2022': 'https://fbref.com/en/comps/48/Superettan-Stats',
                                   '2021': 'https://fbref.com/en/comps/48/11004/2021-Superettan-Stats',
                                   '2020': 'https://fbref.com/en/comps/48/10088/2020-Superettan-Stats',
                                   '2019': 'https://fbref.com/en/comps/48/2919/2019-Superettan-Stats',
                                   '2018': 'https://fbref.com/en/comps/48/1769/2018-Superettan-Stats',
                                   '2017': 'https://fbref.com/en/comps/48/1571/2017-Superettan-Stats',
                                   '2016': 'https://fbref.com/en/comps/48/1510/2016-Superettan-Stats',
                                   '2015': 'https://fbref.com/en/comps/48/1350/2015-Superettan-Stats'},
                          'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                     '//*[@id="stats_squads_keeper_for"]']},
    'SouthKoreaLeague1': {'urls': {'2022': 'https://fbref.com/en/comps/55/K-League-1-Stats',
                                  '2021': 'https://fbref.com/en/comps/55/10997/2021-K-League-1-Stats',
                                  '2020': 'https://fbref.com/en/comps/55/10081/2020-K-League-1-Stats',
                                  '2019': 'https://fbref.com/en/comps/55/3930/2019-K-League-1-Stats',
                                  '2018': 'https://fbref.com/en/comps/55/1771/2018-K-League-1-Stats',
                                  '2017': 'https://fbref.com/en/comps/55/1575/2017-K-League-Classic-Stats',
                                  '2016': 'https://fbref.com/en/comps/55/1508/2016-K-League-Classic-Stats',
                                  '2015': 'https://fbref.com/en/comps/55/1230/2015-K-League-Classic-Stats'},
                         'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                    '//*[@id="stats_squads_keeper_for"]']},
    'PeruLiga1': {'urls': {'2022': 'https://fbref.com/en/comps/44/Liga-1-Stats',
                                   '2021': 'https://fbref.com/en/comps/44/11001/2021-Liga-1-Stats',
                                   '2020': 'https://fbref.com/en/comps/44/10085/2020-Liga-1-Stats',
                                   '2019': 'https://fbref.com/en/comps/44/3928/2019-Liga-1-Stats',
                                   '2018': 'https://fbref.com/en/comps/44/1767/2018-Torneo-Descentralizado-Stats',
                                   '2017': 'https://fbref.com/en/comps/44/1568/2017-Torneo-Descentralizado-Stats',
                                   '2016': 'https://fbref.com/en/comps/44/1507/2016-Torneo-Descentralizado-Stats',
                                   '2015': 'https://fbref.com/en/comps/44/1290/2015-Torneo-Descentralizado-Stats'},
                          'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                     '//*[@id="stats_squads_keeper_for"]']},
    'ParaguayPrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/61/Primera-Division-Stats',
                           '2021': 'https://fbref.com/en/comps/61/11000/2021-Primera-Division-Stats',
                           '2020': 'https://fbref.com/en/comps/61/10084/2020-Primera-Division-Stats',
                           '2019': 'https://fbref.com/en/comps/61/3932/2019-Primera-Division-Stats',
                           '2018': 'https://fbref.com/en/comps/61/1773/2018-Primera-Division-Stats',
                           '2017': 'https://fbref.com/en/comps/61/1577/2017-Primera-Division-Stats',
                           '2016': 'https://fbref.com/en/comps/61/1506/2016-Primera-Division-Stats',
                           '2015': 'https://fbref.com/en/comps/61/1282/2015-Primera-Division-Stats'},
                  'xpaths': ['//*[@id="stats_squads_standard_for"]',
                             '//*[@id="stats_squads_keeper_for"]']},
    'CanadaPremierLeague': {'urls': {'2022': 'https://fbref.com/en/comps/211/Canadian-Premier-League-Stats',
                                         '2021': 'https://fbref.com/en/comps/211/10988/2021-Canadian-Premier-League-Stats',
                                         '2020': 'https://fbref.com/en/comps/211/10139/2020-Canadian-Premier-League-Stats',
                                         '2019': 'https://fbref.com/en/comps/211/3435/2019-Canadian-Premier-League-Stats',
                                         '2018': '',
                                         '2017': '',
                                         '2016': '',
                                         '2015': ''},
                                'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                           '//*[@id="stats_squads_keeper_for"]']},
    'NorwayEliteserien': {'urls': {'2022': 'https://fbref.com/en/comps/28/Eliteserien-Stats',
                                     '2021': 'https://fbref.com/en/comps/28/10998/2021-Eliteserien-Stats',
                                     '2020': 'https://fbref.com/en/comps/28/10082/2020-Eliteserien-Stats',
                                     '2019': 'https://fbref.com/en/comps/28/2897/2019-Eliteserien-Stats',
                                     '2018': 'https://fbref.com/en/comps/28/1762/2018-Eliteserien-Stats',
                                     '2017': 'https://fbref.com/en/comps/28/1561/2017-Eliteserien-Stats',
                                     '2016': 'https://fbref.com/en/comps/28/1505/2016-Tippeligaen-Stats',
                                     '2015': 'https://fbref.com/en/comps/28/1281/2015-Tippeligaen-Stats'},
                            'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                       '//*[@id="stats_squads_keeper_for"]']},
}

odds_portal_multipage = {
    'PeruLiga1': {'2022': 'https://www.oddsportal.com/soccer/peru/liga-1/results/',
                  '2021': 'https://www.oddsportal.com/soccer/peru/liga-1-2021/results/',
                  '2020': 'https://www.oddsportal.com/soccer/peru/liga-1-2020/results/',
                  '2019': 'https://www.oddsportal.com/soccer/peru/liga-1-2019/results/',
                  '2018': 'https://www.oddsportal.com/soccer/peru/primera-division-2018/results/',
                  '2017': 'https://www.oddsportal.com/soccer/peru/primera-division-2017/results/',
                  '2016': 'https://www.oddsportal.com/soccer/peru/primera-division-2016/results/',
                  '2015': 'https://www.oddsportal.com/soccer/peru/primera-division-2015/results/'
                  },
    'SouthKoreaLeague1': {'2022': 'https://www.oddsportal.com/soccer/south-korea/k-league-1/results/',
                  '2021': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2021/results/',
                  '2020': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2020/results/',
                  '2019': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2019/results/',
                  '2018': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2018/results/',
                  '2017': 'https://www.oddsportal.com/soccer/south-korea/k-league-classic-2017/results/',
                  '2016': 'https://www.oddsportal.com/soccer/south-korea/k-league-classic-2016/results/',
                  '2015': 'https://www.oddsportal.com/soccer/south-korea/k-league-classic-2015/results/'
                  },
    'UruguayPrimeraDivision': {'2022': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2021/results/',
                  '2021': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2021/results/',
                  '2020': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2020/results/',
                  '2019': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2019/results/',
                  '2018': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2018/results/',
                  '2017': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2017/results/',
                  '2016': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2016/results/',
                  '2015': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2015-2016/results/'
                  },
}

betonline_url = {'MLB': 'baseball/mlb',
                 'NBA': 'basketball/nba',
                 'NHL': 'hockey/nhl',
                 'EuroLeague': 'basketball/europe/euroleague',
                 'NBLAustralia': 'basketball/australia/australian-nbl',
                 'EuroCup': 'basketball/europe/eurocup',
                 'VTBUnited': 'basketball/russia/vtb-united-league',
                 'SpainACB': 'basketball/spain/spain-acb',
                 'ItalyLega': 'basketball/italy/italy-lega-a',
                 'FranceLNB': 'basketball/france/france-lnb',
                 'GreekBasketball': 'basketball/greece/greece-basket-league',
                 'ATPRome': 'tennis/atp/atp-rome',
                 'WTARome': 'tennis/wta/wta-rome', 'WNBA': 'basketball/wnba',
                 'ATPGeneva': 'tennis/atp/atp-geneva',
                 'ATPLyon': 'tennis/atp/atp-lyon',
                 'WTAStrasbourg': 'tennis/wta/wta-strasbourg',
                 'MLS': 'soccer/mls/major-league-soccer',
                 'EPL': 'soccer/epl/english-premier-league',
                 'ATPFrenchOpen': 'tennis/atp/atp-french-open',
                 'NPB': 'baseball/japan/npb',
                 'BrazilSerieA': 'soccer/brazil/brazil-serie-a',
                 'BrazilSerieB': 'soccer/brazil/brazil-serie-b',
                 'Bundesliga': 'soccer/bundesliga/german-bundesliga',
                 'ChinaSuperLeague': 'soccer/china/china-super-league',
                 'CPBL': 'baseball/chinese-taipei/cpbl',
                 'UruguayPrimeraDivision': 'soccer/uruguay/uruguay-primera-division',
                 'SwedenAllsvenskan': 'soccer/sweden/sweden-allsvenskan',
                 'SwedenSuperettan': 'soccer/sweden/sweden-superettan',
                 'SouthKoreaLeague1': 'soccer/south-korea/south-korea-league-1',
                 'PeruLiga1': 'soccer/peru/peru-liga-1-apertura',
                 'ParaguayPrimeraDivision': 'soccer/paraguay/paraguay-primera-division',
                 'SpanishLaLiga': 'soccer/la-liga/spanish-laliga',
                 'KBO': 'baseball/south-korea/kbo',
                 'MexicanLMB': 'baseball/mexico/lmb'}

soccer_odds_portal_conv = {'San Jose': 'San Jose Earthquakes',
                           'Minnesota Utd': 'Minnesota United',
                           'Seattle': 'Seattle Sounders',
                           'CF Montréal': 'CF Montreal',
                           'Sporting KC': 'Sporting Kansas City',
                           'NY Red Bulls': 'New York Red Bulls',
                           'NYCFC': 'New York City',
                           'D.C. United': 'DC United',
                           'Nashville': 'Nashville SC',
                           'New England': 'New England Revolution',
                           'LA Galaxy': 'Los Angeles Galaxy',
                           'Philadelphia': 'Philadelphia Union',
                           'Vancouver': 'Vancouver Whitecaps',
                           'Leeds United': 'Leeds',
                           'Newcastle Utd': 'Newcastle',
                           'Leicester City': 'Leicester',
                           'América (MG)': 'AmericaMineiro',
                           'Atl Goianiense': 'AtleticoGoianiense',
                           'Atl Paranaense': 'AtleticoParanaense',
                           'Atlético Mineiro': 'AtleticoMG',
                           'Avaí': 'Avai',
                           'Botafogo (RJ)': 'BotafogoRJ',
                           'Corinthians': 'CorinthiansSP',
                           'Coritiba': 'CoritibaPR',
                           'Fluminense': 'FluminenseRJ',
                           'Fortaleza': 'FortalezaEC',
                           'Goiás': 'Goias',
                           'São Paulo': 'Sao Paulo SP',
                           'Palmeiras': 'Palmeiras SP',
                           'CRB': 'CRB Maceio',
                           'Chogqing SWM': 'Chongqing Liangjiang Athletic',
                           'Dalian Professional': 'Dalian Pro',
                           'Guangzhou Evg': 'Guangzhou FC',
                           'Guangzhou R&F': 'Guangzhou City',
                           'Hebei Fortune': 'Hebei',
                           'Henan Jianye': 'Henan Songshan Longmen',
                           'Qingdao Hainiu': 'Qingdao FC',
                           'Shandong Lunen': 'Shandong Taishan',
                           'Shanghai Shen': 'Shanghai Shenhua',
                           'Shanghai SIPG': 'Shanghai Port',
                           'Shijiazhuang Ever Bright': 'Cangzhou',
                           'Tianjin TEDA': 'Tianjin Jinmen Tiger',
                           'Wuhan Zall': 'Wuhan FC',
                           'Guizhou Renhe': 'Beijing Renhe',
                           'Chongqing Lifan': 'Chongqing Liangjiang Athletic',
                           'Liaoning': 'Liaoning Whowin',
                           'Jiangsu Suning': 'Jiangsu Sainty',
                           'Zhejiang Professional': 'Hang Greentown',
                           'Shanghai Shenxin': 'Shanghai Shenx',
                           'Liaoning Whowin': 'Liaoning',
                           'Jiangsu Sainty': 'Jiangsu Suning',
                           'Hang Greentown': 'Zhejiang Professional',
                           'Shanghai Shenx': 'Shanghai Shenxin',
                           'Shiji Ever Bright': 'Cangzhou',
                           'Yanbian Funde': 'Yanbian Longding',
                           'Zhej Greentown': 'Zhejiang Professional',
                           'Wuhan Three Towns FC': 'Wuhan Three Towns',
                           'Chengdu Better City FC': 'Chengdu Rongcheng',
                           'Meizhou Hakka FC': 'Meizhou Hakka',
                           'CSA': 'CSAAL',
                           'Grêmio': 'Gremio',
                           'Ponte Preta': 'PontePretaSP',
                           'Sampaio Corrêa': 'SampaioCorreaMA',
                           'Bahia': 'BahiaBA',
                           'Grêmio Novorizontino': 'Novorizontino',
                           'Santos': 'SantosSP',
                           'Schalke 04': 'Schalke',
                           'Hertha BSC': 'Hertha Berlin',
                           'Arminia': 'Arminia Bielefeld',
                           'Eint Frankfurt': 'Eintracht Frankfurt',
                           'Köln': 'FC Koln',
                           "M'Gladbach": 'B. Monchengladbach',
                           'Mainz 05': 'Mainz',
                           'Leverkusen': 'Bayer Leverkusen',
                           'Düsseldorf': 'Dusseldorf',
                           'Paderborn 07': 'Paderborn',
                           'Ingolstadt 04': 'Ingolstadt',
                           'Darmstadt 98': 'Darmstadt',
                           'Villa Española': 'Villa Espanola',
                           'Sud América': 'Sud America',
                           'Fénix': 'Fenix',
                           'Liverpool': 'Liverpool M.',
                           'Peñarol': 'Penarol',
                           'Torque': 'Montevideo City',
                           'Racing': 'Racing Montevideo',
                           'Defensor': 'Defensor Sp.',
                           'AIK Stockholm': 'AIK',
                           'Djurgården': 'Djurgarden',
                           'Göteborg': 'Goteborg',
                           'Häcken': 'Hacken',
                           'Malmö': 'Malmo FF',
                           'Mjällby': 'Mjallby',
                           'Norrköping': 'Norrkoping',
                           'Örebro': 'Orebro',
                           'Östersund': 'Ostersund',
                           'Jönköping': 'Jonkoping',
                           'Örgryte': 'Orgryte',
                           'Öster': 'Oster',
                           'Västerås': 'Vasteras SK',
                           'Värnamo': 'Varnamo',
                           'Skövde': 'Skovde AIK',
                           'Cerro Porteño': 'Cerro Porteno',
                           'General Díaz': 'Diaz',
                           'Guaireña FC': 'Guairena FC',
                           'Guaraní': 'Guarani',
                           'Libertad': 'Libertad Asuncion',
                           'Olimpia': 'Olimpia Asuncion',
                           'Sol de América': 'Sol de America',
                           'Sport Luqueño': 'Sp. Luqueno',
                           'Akropolis IF': 'Akropolis',
                           'Ljungskile SK': 'Ljungskile',
                           'Umeå FC': 'Umea FC',
                           'Club General Caballero JLM': 'General Caballero JLM',
                           'Resistencia SC': 'Resistencia',
                           'Sportivo Ameliano': 'Ameliano',
                           'Santaní': 'Deportivo Santani',
                           'Capiatá': 'Dep. Capiata',
                           'Independiente': 'Independiente FBC',
                           'Rubio Ñu': 'Rubio Nu',
                           'Trinidense': 'Sportivo Trinidense',
                           'Gen Caballero': 'General Caballero SC',
                           'Alianza Atlético': 'Alianza Atl.',
                           'Asociación Deportiva Tarma': 'ADT Tarma',
                           'Atlético Grau': 'Grau',
                           'Cantolao': 'AD Cantolao',
                           'Dep Municipal': 'Dep. Municipal',
                           'Mannucci': 'Carlos Mannucci',
                           'Melgar': 'FBC Melgar',
                           'U César Vallejo': 'Cesar Vallejo',
                           'Universitario': 'U. de Deportes',
                           'USMP': 'U. San Martin',
                           'UTC': 'Cajamarca',
                           'Alianza Univ': 'Alianza Huanuco',
                           'Unión Comercio': 'Union Comercio',
                           'Real Garcilaso': 'Cusco',
                           'Comerciantes': 'Comerciantes Unidos',
                           'La Bocana': 'Defensor La Bocana',
                           'FC Seoul': 'Seoul',
                           'Gwangju': 'Gwangju FC',
                           'Incheon United': 'Incheon',
                           'Jeju United': 'Jeju Utd',
                           'Sangju Sangmu': 'Gimcheon Sangmu',
                           'Suw Bluewings': 'Suwon Bluewings',
                           "Busan I'Park": 'Busan',
                           'Jeju United FC': 'Jeju Utd',
                           'Åtvidaberg': 'Atvidaberg',
                           'AFC United': 'AFC Eskilstuna',
                           'Ängelholm': 'Angelholm',
                           'Assyriska': 'Assyriska FF',
                           'Albion FC': 'Albion',
                           'CA Cerro': 'Cerro Largo',
                           'Nacional Asuncion': 'Nacional',
                           'Cerro': 'CA Cerro',
                           'El Tanque Sisley': 'Sisley',
                           'AtleticoParanaense': 'Athletico-PR',
                           'AtleticoMG': 'Atletico-MG',
                           'Chapecoense': 'Chapecoense-SC',
                           'CorinthiansSP': 'Corinthians',
                           'CoritibaPR': 'Coritiba',
                           'Flamengo': 'Flamengo RJ',
                           'FluminenseRJ': 'Fluminense',
                           'Palmeiras SP': 'Palmeiras',
                           'SantosSP': 'Santos',
                           'Sao Paulo SP': 'Sao Paulo',
                           'Vasco da Gama': 'Vasco',
}

baseball_odds_portal_conv = {'Arizona Diamondbacks': 'ARI',
                             'Atlanta Braves': 'ATL',
                             'Baltimore Orioles': 'BAL',
                         'Boston Red Sox': 'BOS',
                             'Chicago Cubs': 'CUB',
                             'Chicago White Sox': 'CWS',
                         'Cincinnati Reds': 'CIN',
                         'Cleveland Indians': 'CLE',
                             'Cleveland Guardians': 'CLE',
                             'Colorado Rockies': 'COL',
                             'Detroit Tigers': 'DET',
                         'Houston Astros': 'HOU',
                         'Kansas City Royals': 'KAN',
                             'Los Angeles Angels': 'LAA',
                             'Los Angeles Dodgers': 'LAD',
                         'Miami Marlins': 'MIA',
                             'Milwaukee Brewers': 'MIL',
                             'Minnesota Twins': 'MIN',
                         'New York Mets': 'NYM',
                         'New York Yankees': 'NYY',
                             'Oakland Athletics': 'OAK',
                             'Philadelphia Phillies': 'PHI',
                         'Pittsburgh Pirates': 'PIT',
                             'San Diego Padres': 'SDP',
                             'Seattle Mariners': 'SEA',
                         'San Francisco Giants': 'SFO',
                         'St. Louis Cardinals': 'STL',
                             'Tampa Bay Rays': 'TAM',
                             'Texas Rangers': 'TEX',
                         'Toronto Blue Jays': 'TOR',
                             'Washington Nationals': 'WAS',
                             'Rakuten Monkeys': 'Rakuten',
                             'Uni-President 7-Eleven Lions': 'Uni',
                             'CTBC Brothers': 'Chinatrust',
                         'Wei Chuan Dragons': 'Wei Chuan',
                             'Fubon Guardians': 'Fubon',
                             'Lamigo Monkeys': 'Rakuten',
                         'Chunichi Dragons': 'Chunchi',
                             'Hanshin Tigers': 'Hanshin',
                             'Yakult Swallows': 'Yakult',
                         'Yomiuri Giants': 'Yomiuri',
                             'Hiroshima Carp': 'Hiroshima',
                             'Yokohama Bay Stars': 'Yokohama',
                             'EDA Rhinos': 'Eda',
                             'Chinatrust Brothers': 'Chinatrust',
                             'RakutenMonkeys': 'Rakuten',
                         }

betonline_baseball_conv = {
    'Chinatrust': 'Brother Elephants',
    'Fubon': 'FubonGuardians',
    'WeiChuan': 'WeiChuanDragons',
    'Rakuten': 'RakutenMonkeys',
    'Uni': 'Uni-Lions',
    'HOU': 'HoustonAstros',
    'NYY': 'NewYorkYankees',
    'PIT': 'PittsburghPirates',
    'TAM': 'TampaBayRays',
    'BAL': 'BaltimoreOrioles',
    'CWS': 'ChicagoWhiteSox',
    'CUB': 'ChicagoCubs',
    'STL': 'St.LouisCardinals',
    'TEX': 'TexasRangers',
    'NYM': 'NewYorkMets',
    'MIA': 'MiamiMarlins',
    'OAK': 'OaklandAthletics',
    'KAN': 'KansasCityRoyals',
    'TOR': 'TorontoBlueJays',
    'MIL': 'MilwaukeeBrewers',
    'BOS': 'BostonRedSox',
    'CIN': 'CincinnatiReds',
    'SFO': 'SanFranciscoGiants',
    'LAD': 'LosAngelesDodgers',
    'ATL': 'AtlantaBraves',
    'COL': 'ColoradoRockies',
    'MIN': 'MinnesotaTwins',
    'LAA': 'LosAngelesAngels',
    'PHI': 'PhiladelphiaPhillies',
    'SDP': 'SanDiegoPadres',
    'DET': 'DetroitTigers',
    'ARI': 'ArizonaDiamondbacks',
    'SEA': 'SeattleMariners',
    'WAS': 'WashingtonNationals',
    'CLE': 'ClevelandGuardians'
}

betonline_soccer_conv = {'New York Red Bulls': 'New York RB',
                         'Los Angeles Galaxy': 'LA Galaxy',
                         'CF Montreal': 'Montreal', 'FC Dallas': 'Dallas',
                         'New England Revolution': 'New England',
                         'Toronto FC': 'Toronto',
                         'Atlanta Utd': 'Atlanta United',
                         'Charlotte FC': 'Charlotte',
                         'Zhej Greentown': 'ZhejiangProfessional',
                         'Tianjin Jinmen Tiger': 'TianjinTigers',
                         'Meizhou Hakka FC': 'MeizhouHakka',
                         'Bayern Munich': 'BayernMunchen',
                         'Dortmund': 'BorussiaDortmund',
                         'B. Monchengladbach': 'BorussiaMonchengladbach',
                         'FC Koln': 'Koln',
                         'Stuttgart': 'VfBStuttgart',
                         'Mainz': 'Mainz05',
                         'Vasco da Gama': 'VascoDaGamaRJ',
                         'Operário': 'OperarioPR',
                         'Londrina': 'LondrinaEC',
                         'Sport Recife': 'SportRecifePE',
                         'Brusque Futebol Clube': 'BrusqueSC',
                         'Bragantino': 'RBBragantinoSP',
                         'Criciúma': 'Criciuma',
                         'Vila Nova': 'VilaNovaGO',
                         'AIK': 'AIKStockholm',
                         'Varberg': 'VarbergsBoIS',
                         'Skovde AIK': 'Skovde',
                         'Utsikten': 'UtsiktensBK',
                         'Dalkurd': 'DalkurdFF',
                         'Hebei': 'HebeiCFFC',
                         'Guangzhou FC': 'GuangzhouEvergrande',
                         'Ceará': 'CearaCE',
                         'Cuiabá': 'CuiabaMT',
                         'Tombense Futebol Clube': 'TombenseMG',
                         'Náutico': 'NauticoPE',
                         'Guairena FC': 'Guairena',
                         'Malmo FF': 'Malmo',
                         'Varnamo': 'IFKVarnamo',
                         'Sirius': 'IKSiriusFK',
                         'Goteborg': 'IFKGoteborg',
                         'Jonkoping': 'JonkopingsSodra',
                         'Vasco': 'VascoDaGamaRJ',
                         'Cruzeiro': 'CruzeiroMG',
                         'Chapecoense-SC': 'Chapecoense',
                         'Nacional': 'NacionalAsuncion',
                         'Ameliano': 'SportivoAmeliano',
                         'Dep. Municipal': 'DeportivoMunicipal',
                         'AD Cantolao': 'AcademiaCantolao'
}