import pprint

leagues = {
    'Baseball': ['MLB', 'KBO', 'CPBL'],
    'Basketball': ['WNBA', 'EuroLeague', 'GermanyBBL', 'ItalyLega', 'VTBUnited', 'SuperLig', 'SuperLeague', 'NBA',
                   'NCAABasketball', 'GreekBasketball', 'Eurocup', 'SpainACB', 'FranceLNB', 'NBLAustralia'],
    'Tennis': ['ATPRome', 'WTARome', 'ATPGeneva', 'ATPLyon', 'WTAStrasbourg', 'WTARabat', 'ChallengerShykent2'],
    'Soccer': ['MLS', 'EPL', 'SpanishLaLiga', 'ItalianSerieA', 'FranceLigue1', 'GermanyBundesliga', 'ArgentinaPrimeraDivision', 'BrazilSerieB',
               'ChinaSuperLeague', 'BrazilSerieA', 'UruguayPrimeraDivision', 'SwedenAllsvenskan', 'SwedenSuperettan',
               'SouthKoreaLeague1', 'PeruLiga1', 'ParaguayPrimeraDivision', 'JapanJ2', 'JapanJ1', 'MexicoLigaMX',
               'ChilePrimeraDivision', 'ColombiaPrimeraA'],
    'Football': ['NFL'],
    'Hockey': ['NHL']
}

oddsportal_urls = {
    'WNBA': 'basketball/usa/wnba',
    'BrazilSerieA': 'soccer/brazil/serie-a',
    'ATPRome': 'tennis/italy/atp-rome',
    'WTARome': 'tennis/italy/wta-rome',
    'ATPGeneva': 'tennis/switzerland/atp-geneva',
    'ATPLyon': 'tennis/france/atp-lyon',
    'WTAStrasbourg': 'tennis/france/wta-strasbourg',
    'WTARabat': 'tennis/morocco/wta-rabat',
    'ChallengerShymkent2': 'tennis/kazakhstan/shymkent-2-challenger-men',
    'MLS': 'soccer/usa/mls',
    'EPL': 'soccer/england/premier-league',
    'ATPFrenchOpen': 'tennis/france/atp-french-open',
    'KBO': 'baseball/south-korea/kbo',
    'MexicanLMB': 'baseball/mexico/lmb',
    'EuroLeague': 'basketball/europe/euroleague',
    'GermanyBBL': 'basketball/germany/bbl',
    'ItalyLega': 'basketball/italy/lega-a',
    'VTBUnited': 'basketball/russia/vtb-united-league',
    'SuperLig': 'basketball/turkey/super-lig',
    'SuperLeague': 'basketball/israel/super-league',
    'CPBL': 'baseball/taiwan/cpbl',
    'NPB': 'baseball/japan/npb',
    'BrazilSerieB': 'soccer/brazil/serie-b',
    'ChinaSuperLeague': 'soccer/china/super-league',
    'SwedenAllsvenskan': 'soccer/sweden/allsvenskan',
    'SwedenSuperettan': 'soccer/sweden/superettan',
    'ParaguayPrimeraDivision': 'soccer/paraguay/primera-division',
    'JapanJ2': 'soccer/japan/j2-league',
    'JapanJ1': 'soccer/japan/j1-league'
}

sr_multi_page = {
    'NPB': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=6ffa4c10',
                                            '2021': 'https://www.baseball-reference.com/register/league.cgi?id=0549ac26',
                                            '2020': 'https://www.baseball-reference.com/register/league.cgi?id=4b244907',
                                            '2019': 'https://www.baseball-reference.com/register/league.cgi?id=7f5a1dca',
                                            '2018': 'https://www.baseball-reference.com/register/league.cgi?id=8449fb1b',
                                            '2017': 'https://www.baseball-reference.com/register/league.cgi?id=5ed71981',
                                            '2016': 'https://www.baseball-reference.com/register/league.cgi?id=fa996fac',
                                            '2015': 'https://www.baseball-reference.com/register/league.cgi?id=ef7a4bc6'
                                            },
            'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'KBO': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=8af2b395',
                                '2021': 'https://www.baseball-reference.com/register/league.cgi?id=bc0c5118',
                                '2020': 'https://www.baseball-reference.com/register/league.cgi?id=17edbc3b',
                                '2019': 'https://www.baseball-reference.com/register/league.cgi?id=6a2bec36',
                                '2018': 'https://www.baseball-reference.com/register/league.cgi?id=3ef9029d',
                                '2017': 'https://www.baseball-reference.com/register/league.cgi?id=8aa559d8',
                                '2016': 'https://www.baseball-reference.com/register/league.cgi?id=8f7d6569',
                                '2015': 'https://www.baseball-reference.com/register/league.cgi?id=dffe1d5e'
                                },
                                'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'MexicanLMB': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=73c8b264',
                                '2021': 'https://www.baseball-reference.com/register/league.cgi?id=4d19918d',
                                '2020': '',
                                '2019': 'https://www.baseball-reference.com/register/league.cgi?id=92f1b3e0',
                                '2018': '',
                                '2017': 'https://www.baseball-reference.com/register/league.cgi?id=1a0ab508',
                                '2016': 'https://www.baseball-reference.com/register/league.cgi?id=6939d532',
                                '2015': 'https://www.baseball-reference.com/register/league.cgi?id=60e641d9'
                                },
                                'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'EPL': {'urls': {'2022': 'https://fbref.com/en/comps/9/Premier-League-Stats',
                                '2021': 'https://fbref.com/en/comps/9/10728/2020-2021-Premier-League-Stats',
                                '2020': 'https://fbref.com/en/comps/9/3232/2019-2020-Premier-League-Stats',
                                '2019': 'https://fbref.com/en/comps/9/1889/2018-2019-Premier-League-Stats',
                                '2018': 'https://fbref.com/en/comps/9/1631/2017-2018-Premier-League-Stats',
                                '2017': 'https://fbref.com/en/comps/9/1526/2016-2017-Premier-League-Stats',
                                '2016': 'https://fbref.com/en/comps/9/1467/2015-2016-Premier-League-Stats',
                                '2015': 'https://fbref.com/en/comps/9/733/2014-2015-Premier-League-Stats'
                                },
                                'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'SpanishLaLiga': {'urls': {'2022': 'https://fbref.com/en/comps/12/La-Liga-Stats',
                                   '2021': 'https://fbref.com/en/comps/12/10731/2020-2021-La-Liga-Stats',
                                   '2020': 'https://fbref.com/en/comps/12/3239/2019-2020-La-Liga-Stats',
                                   '2019': 'https://fbref.com/en/comps/12/1886/2018-2019-La-Liga-Stats',
                                   '2018': 'https://fbref.com/en/comps/12/1652/2017-2018-La-Liga-Stats',
                                   '2017': 'https://fbref.com/en/comps/12/1547/2016-2017-La-Liga-Stats',
                                   '2016': 'https://fbref.com/en/comps/12/1488/2015-2016-La-Liga-Stats',
                                   '2015': 'https://fbref.com/en/comps/12/755/2014-2015-La-Liga-Stats'
                                   },
                                   'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'ItalianSerieA': {'urls': {'2022': 'https://fbref.com/en/comps/11/Serie-A-Stats',
                                   '2021': 'https://fbref.com/en/comps/11/10730/2020-2021-Serie-A-Stats',
                                   '2020': 'https://fbref.com/en/comps/11/3260/2019-2020-Serie-A-Stats',
                                   '2019': 'https://fbref.com/en/comps/11/1896/2018-2019-Serie-A-Stats',
                                   '2018': 'https://fbref.com/en/comps/11/1640/2017-2018-Serie-A-Stats',
                                   '2017': 'https://fbref.com/en/comps/11/1535/2016-2017-Serie-A-Stats',
                                   '2016': 'https://fbref.com/en/comps/11/1476/2015-2016-Serie-A-Stats',
                                   '2015': 'https://fbref.com/en/comps/11/742/2014-2015-Serie-A-Stats'
                                   },
                                   'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'FranceLigue1': {'urls': {'2022': 'https://fbref.com/en/comps/13/Ligue-1-Stats',
                                   '2021': 'https://fbref.com/en/comps/13/10732/2020-2021-Ligue-1-Stats',
                                   '2020': 'https://fbref.com/en/comps/13/3243/2019-2020-Ligue-1-Stats',
                                   '2019': 'https://fbref.com/en/comps/13/2104/2018-2019-Ligue-1-Stats',
                                   '2018': 'https://fbref.com/en/comps/13/1632/2017-2018-Ligue-1-Stats',
                                   '2017': 'https://fbref.com/en/comps/13/1527/2016-2017-Ligue-1-Stats',
                                   '2016': 'https://fbref.com/en/comps/13/1468/2015-2016-Ligue-1-Stats',
                                   '2015': 'https://fbref.com/en/comps/13/734/2014-2015-Ligue-1-Stats'
                                   },
                                   'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'GermanyBundesliga': {'urls': {'2022': 'https://fbref.com/en/comps/20/Bundesliga-Stats',
                                       '2021': 'https://fbref.com/en/comps/20/10737/2020-2021-Bundesliga-Stats',
                                       '2020': 'https://fbref.com/en/comps/20/3248/2019-2020-Bundesliga-Stats',
                                       '2019': 'https://fbref.com/en/comps/20/2109/2018-2019-Bundesliga-Stats',
                                       '2018': 'https://fbref.com/en/comps/20/1634/2017-2018-Bundesliga-Stats',
                                       '2017': 'https://fbref.com/en/comps/20/1529/2016-2017-Bundesliga-Stats',
                                       '2016': 'https://fbref.com/en/comps/20/1470/2015-2016-Bundesliga-Stats',
                                       '2015': 'https://fbref.com/en/comps/20/736/2014-2015-Bundesliga-Stats'
                                       },
                                       'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'MLS': {'urls': {'2022': 'https://fbref.com/en/comps/22/Major-League-Soccer-Stats',
                                       '2021': 'https://fbref.com/en/comps/22/11006/2021-Major-League-Soccer-Stats',
                                       '2020': 'https://fbref.com/en/comps/22/10090/2020-Major-League-Soccer-Stats',
                                       '2019': 'https://fbref.com/en/comps/22/2798/2019-Major-League-Soccer-Stats',
                                       '2018': 'https://fbref.com/en/comps/22/1759/2018-Major-League-Soccer-Stats',
                                       '2017': 'https://fbref.com/en/comps/22/1558/2017-Major-League-Soccer-Stats',
                                       '2016': 'https://fbref.com/en/comps/22/1503/2016-Major-League-Soccer-Stats',
                                       '2015': 'https://fbref.com/en/comps/22/1369/2015-Major-League-Soccer-Stats'
                                       },
                                'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'CPBL': {'urls': {'2022': 'https://www.baseball-reference.com/register/league.cgi?id=c6fb0851',
                                 '2021': 'https://www.baseball-reference.com/register/league.cgi?id=cb99eabd',
                                 '2020': 'https://www.baseball-reference.com/register/league.cgi?id=344a0cc6',
                                 '2019': 'https://www.baseball-reference.com/register/league.cgi?id=148c2608',
                                 '2018': 'https://www.baseball-reference.com/register/league.cgi?id=465932ad',
                                 '2017': 'https://www.baseball-reference.com/register/league.cgi?id=997b98a9',
                                 '2016': 'https://www.baseball-reference.com/register/league.cgi?id=4f106647',
                                 '2015': 'https://www.baseball-reference.com/register/league.cgi?id=dafaa05c'
                                 },
                                 'xpaths': ['//*[@id="league_batting"]', '//*[@id="league_pitching"]']},
                        'ArgentinaPrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/21/Primera-Division-Stats',
                                            '2021': 'https://fbref.com/en/comps/21/10738/2021-Primera-Division-Stats',
                                            '2020': 'https://fbref.com/en/comps/21/3211/2019-2020-Superliga-Argentina-Stats',
                                            '2019': 'https://fbref.com/en/comps/21/2436/2018-2019-Superliga-Argentina-Stats',
                                            '2018': 'https://fbref.com/en/comps/21/1659/2017-2018-Superliga-Argentina-Stats',
                                            '2017': 'https://fbref.com/en/comps/21/1554/2016-2017-Primera-Division-Stats',
                                            '2016': 'https://fbref.com/en/comps/21/1494/2016-Primera-Division-Stats',
                                            '2015': 'https://fbref.com/en/comps/21/789/2015-Primera-Division-Stats'
                                            },
                                            'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'BrazilSerieA': {'urls': {'2022': 'https://fbref.com/en/comps/24/Serie-A-Stats',
                                         '2021': 'https://fbref.com/en/comps/24/10986/2021-Serie-A-Stats',
                                         '2020': 'https://fbref.com/en/comps/24/10072/2020-Serie-A-Stats',
                                         '2019': 'https://fbref.com/en/comps/24/3320/2019-Serie-A-Stats',
                                         '2018': 'https://fbref.com/en/comps/24/1760/2018-Serie-A-Stats',
                                         '2017': 'https://fbref.com/en/comps/24/1559/2017-Serie-A-Stats',
                                         '2016': 'https://fbref.com/en/comps/24/1495/2016-Serie-A-Stats',
                                         '2015': 'https://fbref.com/en/comps/24/851/2015-Serie-A-Stats'
                                         },
                                         'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
                        'BrazilSerieB': {'urls': {'2022': 'https://fbref.com/en/comps/38/Serie-B-Stats',
                                            '2021': 'https://fbref.com/en/comps/38/10987/2021-Serie-B-Stats',
                                            '2020': 'https://fbref.com/en/comps/38/10073/2020-Serie-B-Stats',
                                            '2019': 'https://fbref.com/en/comps/38/3321/2019-Serie-B-Stats',
                                            '2018': 'https://fbref.com/en/comps/38/1764/2018-Serie-B-Stats',
                                            '2017': 'https://fbref.com/en/comps/38/1563/2017-Serie-B-Stats',
                                            '2016': 'https://fbref.com/en/comps/38/1496/2016-Serie-B-Stats',
                                            '2015': ''},
                                         'xpaths' : ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
    'ChinaSuperLeague': {'urls': {'2022': 'https://fbref.com/en/comps/62/Chinese-Super-League-Stats',
                              '2021': 'https://fbref.com/en/comps/62/10990/2021-Chinese-Super-League-Stats',
                              '2020': 'https://fbref.com/en/comps/62/10075/2020-Chinese-Super-League-Stats',
                              '2019': 'https://fbref.com/en/comps/62/3933/2019-Chinese-Super-League-Stats',
                              '2018': 'https://fbref.com/en/comps/62/1774/2018-Chinese-Super-League-Stats',
                              '2017': 'https://fbref.com/en/comps/62/1578/2017-Chinese-Super-League-Stats',
                              '2016': 'https://fbref.com/en/comps/62/1497/2016-Chinese-Super-League-Stats',
                              '2015': 'https://fbref.com/en/comps/62/897/2015-Chinese-Super-League-Stats'},
                     'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
    'UruguayPrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/45/Primera-Division-Stats',
                                  '2021': 'https://fbref.com/en/comps/45/11005/2021-Primera-Division-Stats',
                                  '2020': 'https://fbref.com/en/comps/45/10089/2020-Primera-Division-Stats',
                                  '2019': 'https://fbref.com/en/comps/45/3929/2019-Primera-Division-Stats',
                                  '2018': 'https://fbref.com/en/comps/45/1768/2018-Primera-Division-Stats',
                                  '2017': 'https://fbref.com/en/comps/45/1569/2017-Primera-Division-Stats',
                                  '2016': 'https://fbref.com/en/comps/45/1570/2016-Primera-Division-Stats',
                                  '2015': 'https://fbref.com/en/comps/45/1493/2015-2016-Primera-Division-Stats'},
                         'xpaths': ['//*[@id="stats_squads_standard_for"]', '//*[@id="stats_squads_keeper_for"]']},
    'SwedenAllsvenskan': {'urls': {'2022': 'https://fbref.com/en/comps/29/Allsvenskan-Stats',
                                        '2021': 'https://fbref.com/en/comps/29/11002/2021-Allsvenskan-Stats',
                                        '2020': 'https://fbref.com/en/comps/29/10086/2020-Allsvenskan-Stats',
                                        '2019': 'https://fbref.com/en/comps/29/2917/2019-Allsvenskan-Stats',
                                        '2018': 'https://fbref.com/en/comps/29/1763/2018-Allsvenskan-Stats',
                                        '2017': 'https://fbref.com/en/comps/29/1562/2017-Allsvenskan-Stats',
                                        '2016': 'https://fbref.com/en/comps/29/1509/2016-Allsvenskan-Stats',
                                        '2015': 'https://fbref.com/en/comps/29/1348/2015-Allsvenskan-Stats'},
                               'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                          '//*[@id="stats_squads_keeper_for"]']},
    'SwedenSuperettan': {'urls': {'2022': 'https://fbref.com/en/comps/48/Superettan-Stats',
                                   '2021': 'https://fbref.com/en/comps/48/11004/2021-Superettan-Stats',
                                   '2020': 'https://fbref.com/en/comps/48/10088/2020-Superettan-Stats',
                                   '2019': 'https://fbref.com/en/comps/48/2919/2019-Superettan-Stats',
                                   '2018': 'https://fbref.com/en/comps/48/1769/2018-Superettan-Stats',
                                   '2017': 'https://fbref.com/en/comps/48/1571/2017-Superettan-Stats',
                                   '2016': 'https://fbref.com/en/comps/48/1510/2016-Superettan-Stats',
                                   '2015': 'https://fbref.com/en/comps/48/1350/2015-Superettan-Stats'},
                          'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                     '//*[@id="stats_squads_keeper_for"]']},
    'SouthKoreaLeague1': {'urls': {'2022': 'https://fbref.com/en/comps/55/K-League-1-Stats',
                                  '2021': 'https://fbref.com/en/comps/55/10997/2021-K-League-1-Stats',
                                  '2020': 'https://fbref.com/en/comps/55/10081/2020-K-League-1-Stats',
                                  '2019': 'https://fbref.com/en/comps/55/3930/2019-K-League-1-Stats',
                                  '2018': 'https://fbref.com/en/comps/55/1771/2018-K-League-1-Stats',
                                  '2017': 'https://fbref.com/en/comps/55/1575/2017-K-League-Classic-Stats',
                                  '2016': 'https://fbref.com/en/comps/55/1508/2016-K-League-Classic-Stats',
                                  '2015': 'https://fbref.com/en/comps/55/1230/2015-K-League-Classic-Stats'},
                         'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                    '//*[@id="stats_squads_keeper_for"]']},
    'PeruLiga1': {'urls': {'2022': 'https://fbref.com/en/comps/44/Liga-1-Stats',
                                   '2021': 'https://fbref.com/en/comps/44/11001/2021-Liga-1-Stats',
                                   '2020': 'https://fbref.com/en/comps/44/10085/2020-Liga-1-Stats',
                                   '2019': 'https://fbref.com/en/comps/44/3928/2019-Liga-1-Stats',
                                   '2018': 'https://fbref.com/en/comps/44/1767/2018-Torneo-Descentralizado-Stats',
                                   '2017': 'https://fbref.com/en/comps/44/1568/2017-Torneo-Descentralizado-Stats',
                                   '2016': 'https://fbref.com/en/comps/44/1507/2016-Torneo-Descentralizado-Stats',
                                   '2015': 'https://fbref.com/en/comps/44/1290/2015-Torneo-Descentralizado-Stats'},
                          'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                     '//*[@id="stats_squads_keeper_for"]']},
    'ParaguayPrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/61/Primera-Division-Stats',
                           '2021': 'https://fbref.com/en/comps/61/11000/2021-Primera-Division-Stats',
                           '2020': 'https://fbref.com/en/comps/61/10084/2020-Primera-Division-Stats',
                           '2019': 'https://fbref.com/en/comps/61/3932/2019-Primera-Division-Stats',
                           '2018': 'https://fbref.com/en/comps/61/1773/2018-Primera-Division-Stats',
                           '2017': 'https://fbref.com/en/comps/61/1577/2017-Primera-Division-Stats',
                           '2016': 'https://fbref.com/en/comps/61/1506/2016-Primera-Division-Stats',
                           '2015': 'https://fbref.com/en/comps/61/1282/2015-Primera-Division-Stats'},
                  'xpaths': ['//*[@id="stats_squads_standard_for"]',
                             '//*[@id="stats_squads_keeper_for"]']},
    'CanadaPremierLeague': {'urls': {'2022': 'https://fbref.com/en/comps/211/Canadian-Premier-League-Stats',
                                         '2021': 'https://fbref.com/en/comps/211/10988/2021-Canadian-Premier-League-Stats',
                                         '2020': 'https://fbref.com/en/comps/211/10139/2020-Canadian-Premier-League-Stats',
                                         '2019': 'https://fbref.com/en/comps/211/3435/2019-Canadian-Premier-League-Stats',
                                         '2018': '',
                                         '2017': '',
                                         '2016': '',
                                         '2015': ''},
                                'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                           '//*[@id="stats_squads_keeper_for"]']},
    'NorwayEliteserien': {'urls': {'2022': 'https://fbref.com/en/comps/28/Eliteserien-Stats',
                                     '2021': 'https://fbref.com/en/comps/28/10998/2021-Eliteserien-Stats',
                                     '2020': 'https://fbref.com/en/comps/28/10082/2020-Eliteserien-Stats',
                                     '2019': 'https://fbref.com/en/comps/28/2897/2019-Eliteserien-Stats',
                                     '2018': 'https://fbref.com/en/comps/28/1762/2018-Eliteserien-Stats',
                                     '2017': 'https://fbref.com/en/comps/28/1561/2017-Eliteserien-Stats',
                                     '2016': 'https://fbref.com/en/comps/28/1505/2016-Tippeligaen-Stats',
                                     '2015': 'https://fbref.com/en/comps/28/1281/2015-Tippeligaen-Stats'},
                            'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                       '//*[@id="stats_squads_keeper_for"]']},
    'JapanJ2': {'urls': {'2022': 'https://fbref.com/en/comps/49/J2-League-Stats',
                                   '2021': 'https://fbref.com/en/comps/49/10996/2021-J2-League-Stats',
                                   '2020': 'https://fbref.com/en/comps/49/10080/2020-J2-League-Stats',
                                   '2019': 'https://fbref.com/en/comps/49/3924/2019-J2-League-Stats',
                                   '2018': 'https://fbref.com/en/comps/49/1770/2018-J2-League-Stats',
                                   '2017': 'https://fbref.com/en/comps/49/1572/2017-J2-League-Stats',
                                   '2016': 'https://fbref.com/en/comps/49/1502/2016-J2-League-Stats',
                                   '2015': 'https://fbref.com/en/comps/49/1221/2015-J2-League-Stats'},
                          'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                     '//*[@id="stats_squads_keeper_for"]']},
    'JapanJ1': {'urls': {'2022': 'https://fbref.com/en/comps/25/J1-League-Stats',
                         '2021': 'https://fbref.com/en/comps/25/10995/2021-J1-League-Stats',
                         '2020': 'https://fbref.com/en/comps/25/10079/2020-J1-League-Stats',
                         '2019': 'https://fbref.com/en/comps/25/3923/2019-J1-League-Stats',
                         '2018': 'https://fbref.com/en/comps/25/1761/2018-J1-League-Stats',
                         '2017': 'https://fbref.com/en/comps/25/1560/2017-J1-League-Stats',
                         '2016': 'https://fbref.com/en/comps/25/1501/2016-J1-League-Stats',
                         '2015': 'https://fbref.com/en/comps/25/1219/2015-J1-League-Stats'},
                'xpaths': ['//*[@id="stats_squads_standard_for"]',
                           '//*[@id="stats_squads_keeper_for"]']},
    'MexicoLigaMX': {'urls': {'2022': 'https://fbref.com/en/comps/31/Liga-MX-Stats',
                         '2021': 'https://fbref.com/en/comps/31/11239/2021-2022-Liga-MX-Stats',
                         '2020': 'https://fbref.com/en/comps/31/10743/2020-2021-Liga-MX-Stats',
                         '2019': 'https://fbref.com/en/comps/31/3267/2019-2020-Liga-MX-Stats',
                         '2018': 'https://fbref.com/en/comps/31/2252/2018-2019-Liga-MX-Stats',
                         '2017': 'https://fbref.com/en/comps/31/1642/2017-2018-Liga-MX-Stats',
                         '2016': 'https://fbref.com/en/comps/31/1537/2016-2017-Liga-MX-Stats',
                         '2015': 'https://fbref.com/en/comps/31/1478/2015-2016-Liga-MX-Stats'},
                'xpaths': ['//*[@id="stats_squads_standard_for"]',
                           '//*[@id="stats_squads_keeper_for"]']},
    'ChilePrimeraDivision': {'urls': {'2022': 'https://fbref.com/en/comps/35/Primera-Division-Stats',
                              '2021': 'https://fbref.com/en/comps/35/10989/2021-Primera-Division-Stats',
                              '2020': 'https://fbref.com/en/comps/35/10074/2020-Primera-Division-Stats',
                              '2019': 'https://fbref.com/en/comps/35/3926/2019-Primera-Division-Stats',
                              '2018': 'https://fbref.com/en/comps/35/1621/2018-Primera-Division-Stats',
                              '2017': 'https://fbref.com/en/comps/35/1616/2017-Primera-Division-Stats',
                              '2016': 'https://fbref.com/en/comps/35/1516/2016-2017-Primera-Division-Stats',
                              '2015': 'https://fbref.com/en/comps/35/1457/2015-2016-Primera-Division-Stats'},
                     'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                '//*[@id="stats_squads_keeper_for"]']},
    'ColombiaPrimeraA': {'urls': {'2022': 'https://fbref.com/en/comps/41/Categoria-Primera-A-Stats',
                                      '2021': 'https://fbref.com/en/comps/41/10991/2021-Categoria-Primera-A-Stats',
                                      '2020': 'https://fbref.com/en/comps/41/10076/2020-Categoria-Primera-A-Stats',
                                      '2019': 'https://fbref.com/en/comps/41/3927/2019-Categoria-Primera-A-Stats',
                                      '2018': 'https://fbref.com/en/comps/41/1765/2018-Categoria-Primera-A-Stats',
                                      '2017': 'https://fbref.com/en/comps/41/1564/2017-Categoria-Primera-A-Stats',
                                      '2016': 'https://fbref.com/en/comps/41/1498/2016-Categoria-Primera-A-Stats',
                                      '2015': 'https://fbref.com/en/comps/41/907/2015-Categoria-Primera-A-Stats'},
                             'xpaths': ['//*[@id="stats_squads_standard_for"]',
                                        '//*[@id="stats_squads_keeper_for"]']},
}

odds_portal_multipage = {
    'PeruLiga1': {'2022': 'https://www.oddsportal.com/soccer/peru/liga-1/results/',
                  '2021': 'https://www.oddsportal.com/soccer/peru/liga-1-2021/results/',
                  '2020': 'https://www.oddsportal.com/soccer/peru/liga-1-2020/results/',
                  '2019': 'https://www.oddsportal.com/soccer/peru/liga-1-2019/results/',
                  '2018': 'https://www.oddsportal.com/soccer/peru/primera-division-2018/results/',
                  '2017': 'https://www.oddsportal.com/soccer/peru/primera-division-2017/results/',
                  '2016': 'https://www.oddsportal.com/soccer/peru/primera-division-2016/results/',
                  '2015': 'https://www.oddsportal.com/soccer/peru/primera-division-2015/results/'
                  },
    'SouthKoreaLeague1': {'2022': 'https://www.oddsportal.com/soccer/south-korea/k-league-1/results/',
                  '2021': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2021/results/',
                  '2020': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2020/results/',
                  '2019': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2019/results/',
                  '2018': 'https://www.oddsportal.com/soccer/south-korea/k-league-1-2018/results/',
                  '2017': 'https://www.oddsportal.com/soccer/south-korea/k-league-classic-2017/results/',
                  '2016': 'https://www.oddsportal.com/soccer/south-korea/k-league-classic-2016/results/',
                  '2015': 'https://www.oddsportal.com/soccer/south-korea/k-league-classic-2015/results/'
                  },
    'UruguayPrimeraDivision': {'2022': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2021/results/',
                  '2021': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2021/results/',
                  '2020': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2020/results/',
                  '2019': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2019/results/',
                  '2018': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2018/results/',
                  '2017': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2017/results/',
                  '2016': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2016/results/',
                  '2015': 'https://www.oddsportal.com/soccer/uruguay/primera-division-2015-2016/results/'
                  },
    'MexicoLigaMX': {'2022': 'https://www.oddsportal.com/soccer/mexico/liga-mx/results/',
                               '2021': 'https://www.oddsportal.com/soccer/mexico/liga-mx-2021-2022/results/',
                               '2020': 'https://www.oddsportal.com/soccer/mexico/liga-mx-2020-2021/results/',
                               '2019': 'https://www.oddsportal.com/soccer/mexico/liga-mx-2019-2020/results/',
                               '2018': 'https://www.oddsportal.com/soccer/mexico/primera-division-2018-2019/results/',
                               '2017': 'https://www.oddsportal.com/soccer/mexico/primera-division-2017-2018/results/',
                               '2016': 'https://www.oddsportal.com/soccer/mexico/primera-division-2016-2017/results/',
                               '2015': 'https://www.oddsportal.com/soccer/mexico/primera-division-2015-2016/results/'
                               },
    'ChilePrimeraDivision': {'2022': 'https://www.oddsportal.com/soccer/chile/primera-division/results/',
                               '2021': 'https://www.oddsportal.com/soccer/chile/primera-division-2021/results/',
                               '2020': 'https://www.oddsportal.com/soccer/chile/primera-division-2020/results/',
                               '2019': 'https://www.oddsportal.com/soccer/chile/primera-division-2019/results/',
                               '2018': 'https://www.oddsportal.com/soccer/chile/primera-division-2018/results/',
                               '2017': 'https://www.oddsportal.com/soccer/chile/primera-division-2017/results/',
                               '2016': 'https://www.oddsportal.com/soccer/chile/primera-division-2016-2017/results/',
                               '2015': 'https://www.oddsportal.com/soccer/chile/primera-division-2015-2016/results/'
                               },
    'ArgentinaPrimeraDivision': {'2022': 'https://www.oddsportal.com/soccer/argentina/liga-profesional/results/',
                             '2021': 'https://www.oddsportal.com/soccer/argentina/liga-profesional-2021/results/',
                             '2020': 'https://www.oddsportal.com/soccer/argentina/superliga-2019-2020/results/',
                             '2019': 'https://www.oddsportal.com/soccer/argentina/superliga-2018-2019/results/',
                             '2018': 'https://www.oddsportal.com/soccer/argentina/superliga-2017-2018/results/',
                             '2017': 'https://www.oddsportal.com/soccer/argentina/primera-division-2016/results/',
                             '2016': 'https://www.oddsportal.com/soccer/argentina/primera-division-2016-2017/results/',
                             '2015': 'https://www.oddsportal.com/soccer/argentina/primera-division-2015/results/'
                             },
    'ColombiaPrimeraA': {'2022': 'https://www.oddsportal.com/soccer/colombia/primera-a/results/',
                                 '2021': 'https://www.oddsportal.com/soccer/colombia/primera-a-2021/results/',
                                 '2020': 'https://www.oddsportal.com/soccer/colombia/primera-a-2020/results/',
                                 '2019': 'https://www.oddsportal.com/soccer/colombia/liga-aguila-2019/results/',
                                 '2018': 'https://www.oddsportal.com/soccer/colombia/liga-aguila-2018/results/',
                                 '2017': 'https://www.oddsportal.com/soccer/colombia/liga-aguila-2017/results/',
                                 '2016': 'https://www.oddsportal.com/soccer/colombia/liga-aguila-2016/results/',
                                 '2015': 'https://www.oddsportal.com/soccer/colombia/liga-aguila-2015/results/'
                                 },
    'SpanishLaLiga': {'2022': 'https://www.oddsportal.com/soccer/spain/laliga-2021-2022/results/',
                         '2021': 'https://www.oddsportal.com/soccer/spain/laliga-2020-2021/results/',
                         '2020': 'https://www.oddsportal.com/soccer/spain/laliga-2019-2020/results/',
                         '2019': 'https://www.oddsportal.com/soccer/spain/laliga-2018-2019/results/',
                         '2018': 'https://www.oddsportal.com/soccer/spain/laliga-2017-2018/results/',
                         '2017': 'https://www.oddsportal.com/soccer/spain/laliga-2016-2017/results/',
                         '2016': 'https://www.oddsportal.com/soccer/spain/primera-division-2015-2016/results/',
                         '2015': 'https://www.oddsportal.com/soccer/spain/primera-division-2014-2015/results/'
                         },
    'ItalianSerieA': {'2022': 'https://www.oddsportal.com/soccer/italy/serie-a-2021-2022/results/',
                         '2021': 'https://www.oddsportal.com/soccer/italy/serie-a-2020-2021/results/',
                         '2020': 'https://www.oddsportal.com/soccer/italy/serie-a-2019-2020/results/',
                         '2019': 'https://www.oddsportal.com/soccer/italy/serie-a-2018-2019/results/',
                         '2018': 'https://www.oddsportal.com/soccer/italy/serie-a-2017-2018/results/',
                         '2017': 'https://www.oddsportal.com/soccer/italy/serie-a-2016-2017/results/',
                         '2016': 'https://www.oddsportal.com/soccer/italy/serie-a-2015-2016/results/',
                         '2015': 'https://www.oddsportal.com/soccer/italy/serie-a-2014-2015/results/'
                         },
    'FranceLigue1': {'2022': 'https://www.oddsportal.com/soccer/france/ligue-1-2021-2022/results/',
                      '2021': 'https://www.oddsportal.com/soccer/france/ligue-1-2020-2021/results/',
                      '2020': 'https://www.oddsportal.com/soccer/france/ligue-1-2019-2020/results/',
                      '2019': 'https://www.oddsportal.com/soccer/france/ligue-1-2018-2019/results/',
                      '2018': 'https://www.oddsportal.com/soccer/france/ligue-1-2017-2018/results/',
                      '2017': 'https://www.oddsportal.com/soccer/france/ligue-1-2016-2017/results/',
                      '2016': 'https://www.oddsportal.com/soccer/france/ligue-1-2015-2016/results/',
                      '2015': 'https://www.oddsportal.com/soccer/france/ligue-1-2014-2015/results/'
                      },
    'GermanyBundesliga': {'2022': 'https://www.oddsportal.com/soccer/germany/bundesliga-2021-2022/results/',
                     '2021': 'https://www.oddsportal.com/soccer/germany/bundesliga-2020-2021/results/',
                     '2020': 'https://www.oddsportal.com/soccer/germany/bundesliga-2019-2020/results/',
                     '2019': 'https://www.oddsportal.com/soccer/germany/bundesliga-2018-2019/results/',
                     '2018': 'https://www.oddsportal.com/soccer/germany/bundesliga-2017-2018/results/',
                     '2017': 'https://www.oddsportal.com/soccer/germany/bundesliga-2016-2017/results/',
                     '2016': 'https://www.oddsportal.com/soccer/germany/bundesliga-2015-2016/results/',
                     '2015': 'https://www.oddsportal.com/soccer/germany/bundesliga-2014-2015/results/'
                     },
}

betonline_url = {'MLB': 'baseball/mlb',
                 'NBA': 'basketball/nba',
                 'NHL': 'hockey/nhl',
                 'EuroLeague': 'basketball/europe/euroleague',
                 'NBLAustralia': 'basketball/australia/australian-nbl',
                 'EuroCup': 'basketball/europe/eurocup',
                 'VTBUnited': 'basketball/russia/vtb-united-league',
                 'SpainACB': 'basketball/spain/spain-acb',
                 'ItalyLega': 'basketball/italy/italy-lega-a',
                 'FranceLNB': 'basketball/france/france-lnb',
                 'GreekBasketball': 'basketball/greece/greece-basket-league',
                 'ATPRome': 'tennis/atp/atp-rome',
                 'WTARome': 'tennis/wta/wta-rome', 'WNBA': 'basketball/wnba',
                 'ATPGeneva': 'tennis/atp/atp-geneva',
                 'ATPLyon': 'tennis/atp/atp-lyon',
                 'WTAStrasbourg': 'tennis/wta/wta-strasbourg',
                 'MLS': 'soccer/mls/major-league-soccer',
                 'EPL': 'soccer/epl/english-premier-league',
                 'ATPFrenchOpen': 'tennis/atp/atp-french-open',
                 'NPB': 'baseball/japan/npb',
                 'BrazilSerieA': 'soccer/brazil/brazil-serie-a',
                 'BrazilSerieB': 'soccer/brazil/brazil-serie-b',
                 'GermanyBundesliga': 'soccer/bundesliga/german-bundesliga',
                 'ChinaSuperLeague': 'soccer/china/china-super-league',
                 'CPBL': 'baseball/chinese-taipei/cpbl',
                 'UruguayPrimeraDivision': 'soccer/uruguay/uruguay-primera-division',
                 'SwedenAllsvenskan': 'soccer/sweden/sweden-allsvenskan',
                 'SwedenSuperettan': 'soccer/sweden/sweden-superettan',
                 'SouthKoreaLeague1': 'soccer/south-korea/south-korea-league-1',
                 'PeruLiga1': 'soccer/peru/peru-liga-1-apertura',
                 'ParaguayPrimeraDivision': 'soccer/paraguay/paraguay-primera-division',
                 'SpanishLaLiga': 'soccer/la-liga/spanish-laliga',
                 'KBO': 'baseball/south-korea/kbo',
                 'MexicanLMB': 'baseball/mexico/lmb',
                 'JapanJ2': 'soccer/japan/japan-j2-league',
                 'JapanJ1': 'soccer/japan/japan-j1-league',
                 'MexicoLigaMX': 'soccer/mexico/mexico-liga-mx',
                 'ChilePrimeraDivision': 'soccer/chile/chile-primera-b',
                 'ArgentinaPrimeraDivision': 'soccer/argentina/argentina-primera-division',
                 'ColombiaPrimeraA': 'soccer/colombia/colombia-primera-a',
                 'ItalianSerieA': 'soccer/serie-a/italian-serie-a',
                 'FranceLigue1': 'soccer/ligue-1/french-ligue-1'
                 }


soccer_sr_odds_conv = {
    'MexicoLigaMX': {'FC Juárez': 'Juarez',
                     'León': 'Club Leon',
                     'América': 'Club America',
                     'Guadalajara': 'Guadalajara Chivas',
                     'Mazatlán': 'Mazatlan FC',
                     'Querétaro': 'Queretaro',
                     'Tijuana': 'Club Tijuana',
                     'UANL': 'U.A.N.L.- Tigres',
                     'UNAM': 'U.N.A.M.- Pumas',
                     'Atlético': 'Atl. San Luis',
                     'Santos': 'Santos Laguna',
                     'Morelia': 'Atl. Morelia',
                     'Sinaloa': 'Dorados de Sinaloa'
    },
    'ColombiaPrimeraA': {'AD Cali': 'Dep. Cali',
                         'Cortuluá': 'Cortulua',
                         'Pasto': 'Dep. Pasto',
                         'Jaguares': 'Jaguares de Cordoba',
                         'CD América': 'America De Cali',
                         'Boyacá Patriot': 'Patriotas',
                         'Independiente FBC': 'Ind. Medellin',
                         'Alianza': 'Petrolera',
                         'Rionegro': 'Aguilas',
                         'Nacional': 'Atl. Nacional',
                         'Tolima': 'Deportes Tolima',
                         'Uniautónoma': 'Uniautonoma',
                         'Independiente': 'Ind. Medellin',
                         'Boyacá Chicó': 'Chico',
                         'Cúcuta': 'Cucuta',
                         'CA Bucaramanga': 'Bucaramanga',
                         'Fortaleza CEIF': 'Fortaleza',
                         'Expreso Rojo': 'Tigres',
                         'Leones FC': 'Leones',
                         'ADU Magdalena': 'U. Magdalena',
                         'Atlético Huila': 'Huila',
                         'Deportes Quindío': 'Quindio',
                         'Unión Magdalena': 'U. Magdalena'
    },
    'ChilePrimeraDivision': {
                           'Audax Italiano': 'A. Italiano',
                           'Colo-Colo': 'Colo Colo',
                           'Iquique': 'Deportes Iquique',
                           'La Calera': 'Union La Calera',
                           'San Marcos': 'San Marcos de Arica',
                           'U Concepción': 'U. De Concepcion',
                           'Unión Española': 'U. Espanola',
                           'Univ Católica': 'U. Catolica',
                           'Univ Chile': 'U. De Chile',
                           'Wanderers': 'S. Wanderers',
                           'CD Everton': 'Everton',
                           'CD Temuco': 'Deportes Temuco',
                           'Coquimbo Unido': 'Coquimbo',
                           'Deportes Melipilla': 'Melipilla',
                           'Ñublense': 'Nublense',
    },
    'JapanJ1': {
        'Grampus': 'Nagoya Grampus',
        'Kawa Frontale': 'Kawasaki Frontale',
        'Marinos': 'Yokohama F. Marinos',
        'Montedio': 'Montedio Yamagata',
        'S-Pulse': 'Shimizu S-Pulse',
        'Ventforet Kofu': 'Kofu',
        'Sanfrecce': 'Sanfrecce Hiroshima',
        'Júbilo Iwata': 'Iwata',
        'Consa Sapporo': 'Hokkaido Consadole Sapporo',
        'V-V Nagasaki': 'V-Varen Nagasaki',
        'Vortis': 'Tokushima',
        'Kyoto Sanga': 'Kyoto'
    },
    'JapanJ2': {
        'Blaublitz Akita': 'Blaublitz',
        'Fagi Okayama': 'Okayama',
        'FC Ryūkyū': 'Ryukyu',
        'Machida Zelvia': 'Machida',
        'Mito HollyHock': 'Mito',
        'Montedio': 'Montedio Yamagata',
        'Renofa': 'Renofa Yamaguchi',
        'Roasso Kumamoto': 'Kumamoto',
        'Tokyo Verdy': 'Verdy',
        'V-V Nagasaki': 'V-Varen Nagasaki',
        'Ventforet Kofu': 'Kofu',
        'Thespakusatsu Gunma': 'Kusatsu',
        'Vortis': 'Tokushima',
        'Zweigen': 'Kanazawa',
        'JEF United': 'Chiba',
        'Júbilo Iwata': 'Iwata',
        'Kyoto Sanga': 'Kyoto',
        'SC Sagamihara': 'Sagamihara',
        'Ehime FC': 'Ehime',
        'FC Gifu': 'Gifu',
        'Roasso': 'Kumamoto',
        'Grampus': 'Nagoya Grampus',
        'Thespa Gunma': 'Kusatsu',
        'Consa Sapporo': 'Hokkaido Consadole Sapporo',
        'Giravanz': 'Giravanz Kitakyushu',
        'S-Pulse': 'Shimizu S-Pulse'
    },
    'ParaguayPrimeraDivision': {
        'Capiatá': 'Dep. Capiata',
        'Cerro Porteño': 'Cerro Porteno',
        'Gen Caballero': 'General Caballero SC',
        'General Díaz': 'Diaz',
        'Guaraní': 'Guarani',
        'Libertad': 'Libertad Asuncion',
        'Nacional': 'Nacional Asuncion',
        'Olimpia': 'Olimpia Asuncion',
        'River Plate': 'River Plate',
        'Rubio Ñu': 'Rubio Nu',
        'Sol de América': 'Sol de America',
        'Sport Luqueño': 'Sp. Luqueno',
        'Independiente': 'Independiente FBC',
        'Trinidense': 'Sportivo Trinidense',
        'Santaní': 'Deportivo Santani',
        'Guaireña FC': 'Guairena FC',
        'Club General Caballero JLM': 'General Caballero JLM',
        'Resistencia SC': 'Resistencia',
        'Sportivo Ameliano': 'Ameliano'
    },
    'PeruLiga1': {
        'Alianza Atlético': 'Alianza Atl.',
        'Asociación Deportiva Tarma': 'ADT Tarma',
        'Atlético Grau': 'Grau',
        'Cantolao': 'AD Cantolao',
        'Dep Municipal': 'Dep. Municipal',
        'Mannucci': 'Carlos Mannucci',
        'Melgar': 'FBC Melgar',
        'U César Vallejo': 'Cesar Vallejo',
        'USMP': 'U. San Martin',
        'Universitario': 'U. de Deportes',
        'UTC': 'Cajamarca',
        'Alianza Univ': 'Alianza Huanuco',
        'Unión Comercio': 'Union Comercio',
        'Real Garcilaso': 'Cusco',
        'Comerciantes': 'Comerciantes Unidos',
        'La Bocana': 'Defensor La Bocana',
        'León Huánuco': 'Leon de Huanuco'
    },
    'SouthKoreaLeague1': {
        "Busan I'Park": 'Busan',
        'Daejeon Cit': 'Daejeon',
        'Gwangju': 'Gwangju FC',
        'Incheon United': 'Incheon',
        'Jeju United': 'Jeju Utd',
        'FC Seoul': 'Seoul',
        'Jeju United FC': 'Jeju Utd',
        'Sangju Sangmu': 'Gimcheon Sangmu',
        'Suw Bluewings': 'Suwon Bluewings'
    },
    'MLS': {
        'CF Montréal': 'CF Montreal',
        'Charlotte FC': 'Charlotte',
        'Columbus Crew': 'Columbus Crew',
        'D.C. United': 'DC United',
        'LA Galaxy': 'Los Angeles Galaxy',
        'Minnesota Utd': 'Minnesota United',
        'Nashville': 'Nashville SC',
        'New England': 'New England Revolution',
        'NY Red Bulls': 'New York Red Bulls',
        'NYCFC': 'New York City',
        'Philadelphia': 'Philadelphia Union',
        'San Jose': 'San Jose Earthquakes',
        'Seattle': 'Seattle Sounders',
        'Sporting KC': 'Sporting Kansas City',
        'Vancouver': 'Vancouver Whitecaps',
        'Montreal Impact': 'CF Montreal'
    },
    'EPL': {
        'Leeds United': 'Leeds',
        'Leicester City': 'Leicester',
        'Newcastle Utd': 'Newcastle',
        'Norwich City': 'Norwich',
        'Cardiff City': 'Cardiff',
        'Stoke City': 'Stoke',
        'Swansea City': 'Swansea',
        'Newcastle': 'Middlesbrough',
        'Hull City': 'Norwich',
        'Norwich': 'Hull',
        'Middlesbrough': 'Newcastle'
    },
    'SpanishLaLiga': {
        'Alavés': 'Alaves',
        'Atlético Madrid': 'Atl. Madrid',
        'Cádiz': 'Cadiz CF',
        'Granada': 'Granada CF',
        'Athletic Club': 'Ath Bilbao',
        'Leganés': 'Leganes',
        'Málaga': 'Malaga',
        'La Coruña': 'Dep. La Coruna',
        'Sporting Gijón': 'Gijon',
        'Almería': 'Almeria',
        'Córdoba': 'Cordoba'
    },
    'ItalianSerieA': {
        'Hellas Verona': 'Verona',
        'Milan': 'AC Milan',
        'Roma': 'AS Roma',
        'SPAL': 'Spal'
    },
    'FranceLigue1': {
        'Clermont Foot': 'Clermont',
        'Paris S-G': 'Paris SG',
        'Saint-Étienne': 'St Etienne',
        'Nîmes': 'Nimes',
        'Gazélec Ajaccio': 'GFC Ajaccio',
        'Evian': 'Evian TG'
    },
    'GermanyBundesliga': {
        'Arminia': 'Arminia Bielefeld',
        'Eint Frankfurt': 'Eintracht Frankfurt',
        'Greuther Fürth': 'Greuther Furth',
        'Hertha BSC': 'Hertha Berlin',
        'Köln': 'FC Koln',
        'Leverkusen': 'Bayer Leverkusen',
        "M'Gladbach": 'B. Monchengladbach',
        'Mainz 05': 'Mainz',
        'Schalke 04': 'Schalke',
        'Düsseldorf': 'Dusseldorf',
        'Paderborn 07': 'Paderborn',
        'Hannover 96': 'Hannover',
        'Nürnberg': 'Nurnberg',
        'Darmstadt 98': 'Darmstadt',
        'Ingolstadt 04': 'Ingolstadt'
    },
    'ArgentinaPrimeraDivision': {
        'Arsenal': 'Arsenal Sarandi',
        'CC Córdoba': 'Central Cordoba',
        'Vélez Sarsf': 'Velez Sarsfield',
        'Tucumán': 'Atl. Tucuman',
        'Talleres': 'Talleres Cordoba',
        'Sarmiento': 'Sarmiento Junin',
        'Rosario Cent': 'Rosario Central',
        'Argentinos Jun': 'Argentinos Jrs',
        'CA Huracán': 'Huracan',
        'CA Unión': 'Union de Santa Fe',
        'Defensa y Just': 'Defensa y Justicia',
        'Estudiantes': 'Estudiantes L.P.',
        'Gimnasia ELP': 'Gimnasia L.P.',
        "Newell's OB": 'Newells Old Boys',
        'Colón': 'Colon Santa Fe',
        'Lanús': 'Lanus',
        'San Martin': 'San Martin T.',
        'San Martín SJ': 'San Martin S.J.',
        'Chacarita': 'Chacarita Juniors',
        'Club Olimpo': 'Olimpo Bahia Blanca',
        'Rafaela': 'Atl. Rafaela',
        'Talleres Cordoba': 'Argentinos Jrs',
        'Argentinos Jrs': 'Talleres Cordoba',
        'Crucero': 'Crucero del Norte'
    },
    'BrazilSerieB': {
        'Brusque Futebol Clube': 'Brusque',
        'Chapecoense': 'Chapecoense-SC',
        'Criciúma': 'Criciuma',
        'Grêmio': 'Gremio',
        'Grêmio Novorizontino': 'Novorizontino',
        'Guarani': 'Guarani',
        'Náutico': 'Nautico',
        'Operário': 'Operario',
        'Sampaio Corrêa': 'Sampaio Correa',
        'Tombense Futebol Clube': 'Tombense',
        'Vasco da Gama': 'Vasco',
        'Vila Nova': 'Vila Nova FC',
        'Avaí': 'Avai',
        'Botafogo (RJ)': 'Botafogo RJ',
        'Confiança': 'Confianca',
        'Goiás': 'Goias',
        'Vitória': 'Vitoria',
        'América (MG)': 'America MG',
        'Botafogo (SP)': 'Botafogo SP',
        'Cuiabá': 'Cuiaba',
        'Paraná': 'Parana',
        'Atl Goianiense': 'Atletico GO',
        'São Bento': 'Sao Bento',
        'Paysandu': 'Paysandu PA',
        'Brasil (RS)': 'Brasil de Pelotas',
        'Ceará': 'Ceara',
        'Tupi FC': 'Tupi-MG'
    },
    'ChinaSuperLeague': {
        'Chengdu Better City FC': 'Chengdu Rongcheng',
        'Dalian Professional': 'Dalian Pro',
        'Hebei Fortune': 'Hebei',
        'Henan Jianye': 'Henan Songshan Longmen',
        'Meizhou Hakka FC': 'Meizhou Hakka',
        'Shandong Lunen': 'Shandong Taishan',
        'Shanghai Shen': 'Shanghai Shenhua',
        'Tianjin TEDA': 'Tianjin Jinmen Tiger',
        'Wuhan Three Towns FC': 'Wuhan Three Towns',
        'Wuhan Zall': 'Wuhan FC',
        'Zhej Greentown': 'Zhejiang Professional',
        'Shanghai SIPG': 'Shanghai Port',
        'Guangzhou R&F': 'Guangzhou City',
        'Guangzhou Evg': 'Guangzhou FC',
        'Shijiazhuang Ever Bright': 'Cangzhou',
        'Chongqing SWM': 'Chongqing Liangjiang Athletic',
        'Qingdao Hainiu': 'Qingdao FC',
        'Dalian Yifang': 'Dalian Pro',
        'Guizhou Heng': 'Guizhou',
        "Tianjin Q'jiang": 'Tianjin Tianhai',
        'Chongqing Lifan': 'Chongqing Liangjiang Athletic',
        'Liaoning Whowin': 'Liaoning',
        'Yanbian Funde': 'Yanbian Longding',
        'Hang Greentown': 'Zhejiang Professional',
        'Guizhou Renhe': 'Beijing Renhe',
        'Jiangsu Sainty': 'Jiangsu Suning',
        'Shanghai Shenx': 'Shanghai Shenxin',
        'Shiji Ever Bright': 'Cangzhou'
    },
    'BrazilSerieA': {
        'Goiás': 'Goias',
        'América (MG)': 'America MG',
        'Atl Goianiense': 'Atletico GO',
        'Atlético Mineiro': 'Atletico-MG',
        'Avaí': 'Avai',
        'Botafogo (RJ)': 'Botafogo RJ',
        'Ceará': 'Ceara',
        'Cuiabá': 'Cuiaba',
        'Flamengo': 'Flamengo RJ',
        'São Paulo': 'Sao Paulo',
        'Atl Paranaense': 'Athletico-PR',
        'Chapecoense': 'Chapecoense-SC',
        'Grêmio': 'Gremio',
        'Vasco da Gama': 'Vasco',
        'Paraná': 'Parana',
        'Vitória': 'Vitoria'
    },
    'UruguayPrimeraDivision': {
        'Albion FC': 'Albion',
        'Defensor': 'Defensor Sp.',
        'Fénix': 'Fenix',
        'Liverpool': 'Liverpool M.',
        'Peñarol': 'Penarol',
        'Torque': 'Montevideo City',
        'Sud América': 'Sud America',
        'Villa Española': 'Villa Espanola',
        'Cerro': 'CA Cerro',
        'Racing': 'Racing Montevideo',
        'El Tanque Sisley': 'Sisley'
    },
    'SwedenAllsvenskan': {
        'AIK Stockholm': 'AIK',
        'Djurgården': 'Djurgarden',
        'Göteborg': 'Goteborg',
        'Häcken': 'Hacken',
        'Malmö': 'Malmo FF',
        'Mjällby': 'Mjallby',
        'Norrköping': 'Norrkoping',
        'Värnamo': 'Varnamo',
        'Örebro': 'Orebro',
        'Östersund': 'Ostersund',
        'Jönköping': 'Jonkoping',
        'Åtvidaberg': 'Atvidaberg'
    },
    'SwedenSuperettan': {
        'Jönköping': 'Jonkoping',
        'Örebro': 'Orebro',
        'Örgryte': 'Orgryte',
        'Öster': 'Oster',
        'Östersund': 'Ostersund',
        'Skövde': 'Skovde AIK',
        'Västerås': 'Vasteras SK',
        'Akropolis IF': 'Akropolis',
        'Värnamo': 'Varnamo',
        'Ljungskile SK': 'Ljungskile',
        'Umeå FC': 'Umea FC',
        'Mjällby': 'Mjallby',
        'Åtvidaberg': 'Atvidaberg',
        'AFC United': 'AFC Eskilstuna',
        'Ängelholm': 'Angelholm',
        'Assyriska': 'Assyriska FF'
    }
}

baseball_sr_odds_conv = {
    'KBO': {
        'Kiwoom Heroes': 'Kiwoom',
        'SSG Landers': 'SSG',
        'LG Twins': 'LG',
        'NC Dinos': 'NC',
        'Samsung Lions': 'Samsung',
        'Doosan Bears': 'Doosan',
        'Kia Tigers': 'KIA',
        'Lotte Giants': 'Lotte',
        'Hanwha Eagles': 'Hanwha',
        'SK Wyverns': 'SSG',
        'Nexen Heroes': 'Kiwoom'
    },
    'CPBL': {
        'Rakuten Monkeys': 'Rakuten',
        'CTBC Brothers': 'Chinatrust',
        'Uni-President 7-Eleven Lions': 'Uni',
        'Wei Chuan Dragons': 'Wei Chuan',
        'Fubon Guardians': 'Fubon',
        'Lamigo Monkeys': 'Rakuten',
        'Chinatrust Brothers': 'Chinatrust',
        'EDA Rhinos': 'Eda'
    },
    'MLB': {
        'Arizona Diamondbacks': 'ARI',
                             'Atlanta Braves': 'ATL',
                             'Baltimore Orioles': 'BAL',
                         'Boston Red Sox': 'BOS',
                             'Chicago Cubs': 'CUB',
                             'Chicago White Sox': 'CWS',
                         'Cincinnati Reds': 'CIN',
                         'Cleveland Indians': 'CLE',
                             'Cleveland Guardians': 'CLE',
                             'Colorado Rockies': 'COL',
                             'Detroit Tigers': 'DET',
                         'Houston Astros': 'HOU',
                         'Kansas City Royals': 'KAN',
                             'Los Angeles Angels': 'LAA',
                             'Los Angeles Dodgers': 'LAD',
                         'Miami Marlins': 'MIA',
                             'Milwaukee Brewers': 'MIL',
                             'Minnesota Twins': 'MIN',
                         'New York Mets': 'NYM',
                         'New York Yankees': 'NYY',
                             'Oakland Athletics': 'OAK',
                             'Philadelphia Phillies': 'PHI',
                         'Pittsburgh Pirates': 'PIT',
                             'San Diego Padres': 'SDG',
                             'Seattle Mariners': 'SEA',
                         'San Francisco Giants': 'SFO',
                         'St. Louis Cardinals': 'STL',
                             'Tampa Bay Rays': 'TAM',
                             'Texas Rangers': 'TEX',
                         'Toronto Blue Jays': 'TOR',
                             'Washington Nationals': 'WAS',
    }
}

betonline_baseball_conv = {
    'Chinatrust': 'Brother Elephants',
    'Fubon': 'FubonGuardians',
    'Wei Chuan': 'WeiChuanDragons',
    'Rakuten': 'RakutenMonkeys',
    'Uni': 'Uni-Lions',
    'HOU': 'HoustonAstros',
    'NYY': 'NewYorkYankees',
    'PIT': 'PittsburghPirates',
    'TAM': 'TampaBayRays',
    'BAL': 'BaltimoreOrioles',
    'CWS': 'ChicagoWhiteSox',
    'CUB': 'ChicagoCubs',
    'STL': 'St.LouisCardinals',
    'TEX': 'TexasRangers',
    'NYM': 'NewYorkMets',
    'MIA': 'MiamiMarlins',
    'OAK': 'OaklandAthletics',
    'KAN': 'KansasCityRoyals',
    'TOR': 'TorontoBlueJays',
    'MIL': 'MilwaukeeBrewers',
    'BOS': 'BostonRedSox',
    'CIN': 'CincinnatiReds',
    'SFO': 'SanFranciscoGiants',
    'LAD': 'LosAngelesDodgers',
    'ATL': 'AtlantaBraves',
    'COL': 'ColoradoRockies',
    'MIN': 'MinnesotaTwins',
    'LAA': 'LosAngelesAngels',
    'PHI': 'PhiladelphiaPhillies',
    'SDP': 'SanDiegoPadres',
    'DET': 'DetroitTigers',
    'ARI': 'ArizonaDiamondbacks',
    'SEA': 'SeattleMariners',
    'WAS': 'WashingtonNationals',
    'CLE': 'ClevelandGuardians',
    'Lotte': 'LotteGiants',
    'SSG': 'SSGLanders',
    'LG': 'LGTwins',
    'Samsung': 'SamsungLions',
    'Kiwoom': 'KiwoomHeroes',
    'Doosan': 'DoosanBears',
    'NC': 'NCDinos',
    'Hanwha': 'HanwhaEagles',
    'KIA': 'KiaTigers'
}

soccer_sr_betonline_conv = {
    'BrazilSerieB': {
        'Brusque': 'BrusqueSC',
        'Cruzeiro': 'CruzeiroMG',
        'Chapecoense-SC': 'Chapecoense',
        'Ituano': 'ItuanoSP',
        'Vasco': 'VascoDaGamaRJ',
        'Londrina': 'LondrinaEC',
        'Guarani': 'GuaranideCampinas',
        'Sport Recife': 'SportRecifePE',
        'Tombense': 'TombenseMG',
        'Sampaio Correa': 'SampaioCorreaMA'
    },
    'ChinaSuperLeague': {
        'Cangzhou': 'CangzhouMightyLions',
        'Guangzhou FC': 'GuangzhouEvergrande',
        'Hebei': 'HebeiCFFC',
        'Tianjin Jinmen Tiger': 'TianjinTigers',
        'Wuhan FC': 'WuhanYangtze'
    },
    'JapanJ1': {
        'Nagoya Grampus': 'NagoyaGrampusEight',
        'Shimizu S-Pulse': 'Shimizu',
        'Iwata': 'JubiloIwata',
        'Hokkaido Consadole Sapporo': 'Sapporo',
        'Urawa Reds': 'Urawa',
        'Kawasaki Frontale': 'Kawasaki'
    },
    'JapanJ2': {
        'Grulla Morioka': 'GrullaMarioka',
        'Tochigi SC': 'Tochigi',
        'Verdy': 'TokyoVerdy',
        'Kofu': 'VentforetKofu',
        'Tokushima': 'TokushimaVortis',
        'Kanazawa': 'ZweigenKanazawa',
        'Kusatsu': 'ThespaKusatsu',
        'Blaublitz': 'BlaublitzAkita',
        'Chiba': 'JEFUnited',
        'Machida': 'MachidaZelvia',
        'Mito': 'MitoHollyhock'
    },
    'SouthKoreaLeague1': {
        'Suwon Bluewings': 'SuwonBlueWings',
        'Incheon': 'IncheonUnited',
        'Suwon FC': 'Suwon',
        'Jeju Utd': 'JejuUnited',
        'Seongnam': 'SeongnamIlhwa',
        'Ulsan Hyundai': 'UlsanHyundaiHorang-i'
    },
    'ChilePrimeraDivision': {
    },
    'ArgentinaPrimeraDivision': {
        'Patronato': 'PatronatoParana',
        'Arsenal Sarandi': 'ArsenaldeSarandi',
        'Union de Santa Fe': 'UnionSantaFe',
        'Atl. Tucuman': 'AtleticoTucuman',
        'Gimnasia L.P.': 'GimnasiaLP',
        'Talleres Cordoba': 'Talleres',
        'Newells Old Boys': "Newell'sOldBoys"
    },
    'BrazilSerieA': {
        'Bragantino': 'RBBragantinoSP',
        'Fluminense': 'FluminenseRJ',
        'Ceara': 'CearaCE',
        'Atletico GO': 'AtleticoGoianiense',
        'Atletico-MG': 'AtleticoMG',
        'Athletico-PR': 'AtleticoParanaense',
        'Sao Paulo': 'SaoPauloSP',
        'Santos': 'SantosSP',
        'Cuiaba': 'CuiabaMT',
    },
    'ColombiaPrimeraA': {
        'America De Cali': 'AmericadeCali',
        'Dep. Pasto': 'DeportivoPasto',
        'Bucaramanga': 'AtleticoBucaramanga',
        'Aguilas': 'AguilasDoradas',
        'Dep. Cali': 'DeportivoCali'
    }
}